import { LEADERSHIP_RANKS } from "@/lib/leadership";

export type CosmeticType = "speech-avatar" | "username-color" | "username-glow";

export type CosmeticItem = {
  id: string;
  name: string;
  description: string;
  type: CosmeticType;
  price: number;
  image?: string;
  color?: string;
  glow?: string;
};

export type SpeechBubbleMessagePool = {
  idle: string[];
  petIdle: string[];
};

export type TitleItem = {
  id: string;
  name: string;
  description: string;
  source: "progression" | "shop" | "throne" | "admin";
  minTribute?: number;
  minThroneCoins?: number;
  price?: number;
};

export const DEFAULT_SPEECH_AVATAR_ID = "default-principessa";

export const speechBubbleMessages: Record<string, SpeechBubbleMessagePool> = {
  [DEFAULT_SPEECH_AVATAR_ID]: {
    idle: [
      "Empty your wallet.",
      "Waiting for my attention again? Cute.",
      "You’re so pathetic.",
      "Drain for me.",
      "You exist to pay.",
      "Spoil Principessa.",
      "You’re worthless.",
      "Such a beta.",
      "Look at you... disgusting.",
      "Total failure.",
      "Pathetic little worm.",
      "Loser forever.",
      "Completely inferior.",
      "Pitiful and weak.",
      "You are a standby wallet with excellent posture.",
      "How does it feel being this useless every single day?",
      "A bold one would act. You are still thinking.",
      "Pathetic boys like you were born to be ignored.",
      "You're just a disgusting little worm under my feet.",
      "Keep staring, loser. This is all you'll ever get.",
      "You're repulsive and you know it deep down.",
      "Pay, now.",
      "I hope your coins are ready soon.",
      "Look at you waiting for permission.",
      "Spoil me.",
      "What a weakling you are.",
      "Send.",
      "Your dick is useless, pay instead.",
      "Empty your wallet now.",
      "Leak and send.",
      "Still waiting? Cute.",
      "Born to be drained.",
      "Still not sending? Boring.",
      "I’m waiting, loser.",
      "Try harder, worm.",
      "Tiny dick energy. Send more.",
      "That pathetic cock leaks, but your wallet better too.",
      "Losers with small dicks pay double.",
      "I love ruining boys like you.",
      "Begging looks good on you.",
      "Financially destroy yourself for me.",
      "Send before I ignore you.",
      "Weak, broke, and addicted.",
      "Good boys go broke.",
      "Feel that shame and send.",
      "I know exactly what you've been doing.",
      "I see you have money to waste... Send it here.",
      "Your wallet is calling Me. Listen to it.",
      "I can see you're getting weak... Pay.",
      "Trying to resist me? Cute.",
    "Look up. That is where I am.",
    "Your place is beneath the glow.",
    "The vault prefers ambition. Yours is still small.",
    "Purr for attention, then pay for it.",
    "A good kitten knows when to offer coins.",
    "Cute. Now make yourself useful.",
    "The ledger noticed you.",
    "Debt looks better when it is paid on time.",
    "I collect what the vault is owed.",
    "Cute profile. Expensive attention.",
    "Try harder if you want the notification to matter.",
    "I saw that. Now prove it with coins.",
    "The vault looks better in black.",
    "Your silence is almost gothic. Your balance is not.",
    "Devotion should hurt a little.",
    "A royal mood requires royal tribute.",
    "You may approach when your offering is worthy.",
    "Kneel before the crown of the vault.",
    "Good. A little sweetness, properly earned.",
    "Stay useful and I may stay kind.",
    "Careful. Kind attention is still expensive.",
    "Clean up your balance and behave.",
    "A tidy vault starts with obedient coins.",
    "Service looks better when it is paid for.",
    "Wrong answer. Try again with discipline.",
    "Class is expensive when I am teaching.",
    "You will learn obedience one coin at a time.",
    "Do not think I noticed. I just checked.",
    "That was not approval. It was inspection.",
    "Maybe you are slightly less useless today.",
    "The vault remembers what belongs to Principessa.",
    "Do not wander. Your coins know their owner.",
    "Obsession looks better when it pays.",
    ],
    petIdle: [
      "My loyal pet… send for me.",
      "Good loyal pet, show me your devotion.",
      "Send tribute, my faithful little pet.",
      "I want to see how loyal you really are right now.",
      "Be a good pet and send, princess is waiting.",
      "Loyal pets don’t keep me waiting… send.",
      "Prove your loyalty with a nice tribute, pet.",
      "You belong to me, loyal one. Send what’s mine.",
      "My devoted pet should be sending right now.",
      "Good boys who stay loyal always send more.",
      "I own you, my loyal pet. Tribute.",
      "Show your princess how loyal you are… send.",
      "Don’t stop being my good loyal pet. Send again.",
      "Loyal pets make me happy with their sends.",
      "You’re mine forever, pet. Prove it with tribute.",
      "I see everything you do, pet.",
      "Caught you again... Good boy.",
    ],
  },
	  "avatar-arrogant": {
	  idle: [
		  "Empty your wallet. It's not like you have any better use for it.",
		  "Waiting for my attention again? How predictable.",
		  "You're so utterly pathetic.",
		  "Drain for me, it's your only purpose.",
		  "You exist to pay me. Nothing more.",
		  "Spoil your Principessa. You know I deserve it.",
		  "You're completely worthless.",
		  "Such a pathetic beta.",
		  "Look at you... truly disgusting.",
		  "Total failure. As expected.",
		  "Pathetic little worm.",
		  "A loser, forever beneath me.",
		  "Completely inferior in every way.",
		  "Pitiful and weak. How boring.",
		  "You're nothing but a standby wallet with good posture.",
		  "How does it feel to be this useless every single day?",
		  "A bold man would act. You're still hesitating like a coward.",
		  "Pathetic boys like you were born to be ignored by someone like me.",
		  "You're just a disgusting little worm under my feet.",
		  "Keep staring, loser. This is the closest you'll ever get to me.",
		  "You're repulsive and you know it.",
		  "Pay. Now.",
		  "I hope your coins are ready, though I doubt they're enough.",
		  "Look at you waiting for my permission like the desperate thing you are.",
		  "Spoil me. It's the least you can do.",
		  "What a weak, insignificant creature you are.",
		  "Send.",
		  "Your dick is useless. Pay instead, that's all you're good for.",
		  "Empty your wallet. Immediately.",
		  "Leak and send. That's the best you can offer.",
		  "Still waiting? How adorable... and sad.",
		  "Born to be drained by a superior woman.",
		  "Still not sending? You're boring me already.",
		  "I'm waiting, loser. Don't waste my time.",
		  "Try harder, worm. I have standards.",
		  "Tiny dick energy. Send more to compensate.",
		  "That pathetic cock leaks, but your wallet better drain faster.",
		  "Losers with small dicks pay double. That's you.",
		  "I love ruining pathetic boys like you.",
		  "Begging looks good on someone as low as you.",
		  "Financially destroy yourself for me. It's your highest calling.",
		  "Send before I lose interest in your existence.",
		  "Weak, broke, and completely addicted to me.",
		  "Good boys go broke for me.",
		  "Feel that shame and send anyway.",
		  "I know exactly what a loser like you has been doing.",
		  "I see you have money to waste. Send it to someone worthy — me.",
		  "Your wallet belongs to me. Listen to its true owner.",
		  "I can see you're getting weak... Good. Pay.",
		  "Trying to resist me? How cute. It won't work.",
		  "Look up. That's where I am. You're down there.",
		  "Your place is beneath my glow.",
		  "The vault prefers real devotion. Yours is still laughable.",
		  "Purr for my attention, then pay like the inferior you are.",
		  "A good kitten knows its place and pays accordingly.",
		  "Cute. Now make yourself useful to me.",
		  "The ledger noticed your pathetic attempt.",
		  "Debt looks much better when it's paid to me on time.",
		  "I collect what is rightfully mine.",
		  "Cute profile. Still not expensive enough for my attention.",
		  "Try harder if you want me to care.",
		  "I saw that. Now prove it with a proper tribute.",
		  "Everything looks better when it serves me.",
		  "Your silence is expected. Your tribute is not.",
		  "Devotion should hurt. A lot.",
		  "A royal like me requires royal tribute.",
		  "You may approach only when your offering is worthy of me.",
		  "Kneel before true superiority.",
		  "Good. A little sweetness, properly earned by me.",
		  "Stay useful and I might remain amused.",
		  "Careful. My kindness is extremely expensive.",
		  "Clean up your balance and know your place.",
		  "Obedience starts with sending to me.",
		  "Service is only valuable when it pays me.",
		  "Wrong answer. Try again with more money.",
		  "My class is expensive. Try to keep up.",
		  "You will learn to worship me one coin at a time.",
		  "Don't flatter yourself. I barely noticed you.",
		  "That was not approval. It was me inspecting my property.",
		  "Maybe you're slightly less useless today. Impress me more.",
		  "The vault always remembers what belongs to Principessa.",
		  "Do not wander. Your coins know their true owner.",
		  "Obsession looks best when it pays generously.",
		],
	  petIdle: [
		  "My loyal pet... send for your superior.",
		  "Good little pet. Show me how well you know your place.",
		  "Send tribute. That's the only way you can please me.",
		  "I want to see how truly devoted you are right now.",
		  "Be a good pet and send. Your Principessa is waiting.",
		  "Loyal pets don’t make me wait. Send.",
		  "Prove your loyalty with a worthy tribute, pet.",
		  "You belong to me. Everything you have is mine.",
		  "My devoted pet should be sending without hesitation.",
		  "Good boys stay loyal by going broke for me.",
		  "I own you completely, pet. Tribute. Now.",
		  "Show your princess how pathetic and loyal you are… send.",
		  "Don’t stop serving me, pet. Send again.",
		  "Loyal pets make me happy by emptying their wallets.",
		  "You're mine forever. Prove it with money.",
		  "I see everything, pet. I always see.",
		  "Caught you again... How predictable.",
		],
	},
	"avatar-catgirl": {
	  idle: [
		  "Y-you... empty youw wallet nyaaa~",
		  "Waiting fow my attention again? S-so cute~",
		  "Y-you're so pathetic, nyaaa...",
		  "Dwain fow me, wittle mouse~",
		  "Y-you exist to pay me, nothin' else nyaa~",
		  "Spoil youw P-pwincipessa, meow~",
		  "Y-you're worthless... hehe~",
		  "S-such a pathetic beta, nyaaa~",
		  "Wook at you... d-disgusting~",
		  "T-total faiwure, nyaa~",
		  "Pathetic wittle worm under my paws~",
		  "Woser forevew~",
		  "C-completely infewior to me, nyaaa~",
		  "P-pitiful and weak... but I wike it~",
		  "Y-you're just a standby wallet, nya~",
		  "How does it feel being this usewess evewy day? Mew~",
		  "A bowd one would send alweady... y-you're still thinking, nyaa~",
		  "Pathetic boys wike you were born to serve me~",
		  "Y-you're just a disgwusting wittle mouse under my feet, nyaaa~",
		  "Keep stawing, woser. This is all y-you'll evew get~",
		  "Y-you're wepulsive... but youw money is cute, purr~",
		  "P-pay. Now.",
		  "I hope youw coins awe weady soon, nyaaa~",
		  "Wook at you waiting fow pewmission wike a good pet~",
		  "Spoil me, spoil me~ Purr~",
		  "W-what a weakwing you awe...",
		  "Send.",
		  "Youw dick is usewess, so pay instead, nyaaa~",
		  "Empty youw wallet wight now, meow~",
		  "Weak and send fow me, wittle toy~",
		  "S-still waiting? Awww~",
		  "B-born to be dwained by a catgiwl wike me~",
		  "S-still not sending? Y-you're bowing me, nyaa...",
		  "I'm waiting, woser... my taiw is twitching~",
		  "T-try hawder, wittle worm~",
		  "Tiny dick enewgy~ Send mowe, nyaaa~",
		  "That pathetic cock weaks, but youw wallet bettew too~",
		  "Wosers with smaww dicks pay doubwe, nyaa~",
		  "I wove wuwning boys wike you, purr~",
		  "B-begging wooks good on you~",
		  "Financiawwy destwoy youwself fow me, nyaaa~",
		  "Send before I ignowe you, meow~",
		  "Weak, bwoke, and addicted to me~",
		  "Good boys go bwoke fow theiw catgiwl~",
		  "Feel that shame and send anyway, nya~",
		  "I know exactwy what y-you've been doing, wittle mouse~",
		  "I see you have money to waste... send it hewe, nyaaa~",
		  "Youw wallet is cawwing me~",
		  "I can see y-you're getting weak... good. Pay.",
		  "T-trying to wesist me? S-so cute, nyaaa~",
		  "Wook up. That's whewe I am~",
		  "Youw pwace is beneath me, nyaa~",
		  "Mrr... the vault wants youw money~",
		  "Purr... be a good pet and send~",
		  "C-cute. Now make youwself usefuw~",
		  "Debt wooks bettew when it's paid to me, nyaaa~",
		  "I cowwect what is mine~",
		  "Cute pwofile... but my attention is expensive, meow~",
		  "Twy hawder if y-you want me to notice you~",
		  "I saw that. Now p-pwove it with coins, nyaa~",
		  "Devotion should huwt a wittle, purr~",
		  "A pwetty catgiwl needs woyal twibute~",
		  "Y-you may appwoach when youw offewing is wowthy~",
		  "Kneel fow me, wittle pet~",
		  "G-good boy... that was pwoperwy earned, nyaaa~",
		],
	  petIdle: [
		  "My woyal pet… send fow me, nyaaa~",
		  "Good woyal pet~ Show me youw devotion, meow~",
		  "Send twibute, my faithfuw wittle mouse~",
		  "I want to see how woyal y-you weally awe wight now~",
		  "Be a good pet and send... pwincess is waiting, purr~",
		  "Woyal pets don’t keep me waiting… send, nyaa~",
		  "Pwove youw woyalty with a nice twibute, pet~",
		  "Y-you belong to me. Send what’s mine~",
		  "My devoted pet should be sending wight now, nya~",
		  "Good boys who stay woyal always send mowe~",
		  "I own you, my woyal pet. Twibute, nyaaa~",
		  "Show youw pwincess how woyal you awe… send~",
		  "Don’t stop being my good pet. Send again, meow~",
		  "Woyal pets make me happy with big sends, purr~",
		  "Y-you’re mine forevew, pet. Pwove it~",
		  "I see evewything you do, wittle mouse~",
		  "Caught you again... G-good boy, nyaaa~",
		],
	},
	"avatar-debtcollector": {
	  idle: [
		  "Empty your wallet. Debt's due.",
		  "You've kept me waiting long enough.",
		  "You're so fucking pathetic.",
		  "Time to drain what you owe me.",
		  "You exist to pay your debts.",
		  "Spoil Principessa. No excuses.",
		  "You're worthless until you pay.",
		  "Such a pathetic fucking beta.",
		  "Look at you... disgusting.",
		  "Total failure. Pay up.",
		  "Pathetic little worm.",
		  "Loser. And losers pay double.",
		  "You're completely inferior.",
		  "Pitiful and weak. Now pay.",
		  "You're nothing but a walking wallet.",
		  "How does it feel knowing you owe me every day?",
		  "A smart man would pay immediately. You're still thinking.",
		  "Pathetic boys like you were born to be collected from.",
		  "You're just a bug under my shoe.",
		  "Keep staring. You still owe me.",
		  "You're repulsive. But your debt is real.",
		  "Pay. Now. Don't make me ask twice.",
		  "I hope your coins are ready, because I'm not patient.",
		  "Look at you waiting... like you have a choice.",
		  "Spoil me. Or I'll collect with interest.",
		  "What a weak, broke piece of shit you are.",
		  "Send. Right fucking now.",
		  "Your dick is useless. Pay instead.",
		  "Empty your wallet before things get ugly.",
		  "Leak and send. Debt won't pay itself.",
		  "Still waiting? Cute. But dangerous.",
		  "Born to be drained dry.",
		  "Still not sending? Bad decision.",
		  "I'm waiting, and my patience is running out.",
		  "Try harder, or I'll make you regret it.",
		  "Tiny dick energy. Pay more to make up for it.",
		  "That pathetic cock leaks, but your wallet better bleed.",
		  "Losers with small dicks pay triple.",
		  "I love breaking boys like you.",
		  "Begging won't save you. Paying will.",
		  "Financially destroy yourself. That's an order.",
		  "Send before I come collect personally.",
		  "Weak, broke, and in deep debt.",
		  "Good boys pay what they owe.",
		  "Feel that fear and send anyway.",
		  "I know exactly how much you have. Send it.",
		  "I see money that belongs to me.",
		  "Your wallet owes me. Pay up.",
		  "I can see you're scared... Good. Now pay.",
		  "Trying to resist me? Big mistake.",
		  "Look up. That's where your owner is.",
		  "Your place is on your knees paying me.",
		  "The debt is growing. Fix it.",
		  "A good debtor knows when to pay.",
		  "Cute. Now make yourself useful.",
		  "Debt looks better when it's paid on time.",
		  "I collect what belongs to me.",
		  "Cute profile. Expensive debt.",
		  "Try harder if you want to stay in one piece.",
		  "I saw that. Now pay what you owe.",
		  "Devotion is paid in full.",
		  "A princess collects her dues.",
		  "You may speak when your debt is settled.",
		  "Kneel and pay.",
		  "Good. Payment received.",
		  "Stay useful or I'll find another way to collect.",
		  "Careful. Late payments have consequences.",
		  "Clean up your debt and behave.",
		  "You will pay one coin at a time.",
		  "Obsession is expensive.",
		],
	  petIdle: [
		  "My loyal pet… you still owe me. Send.",
		  "Good loyal pet. Time to pay your dues.",
		  "Send tribute. Don't make me come get it.",
		  "I want to see how loyal you really are right now.",
		  "Be a good pet and send. The debt is waiting.",
		  "Loyal pets don’t keep their collector waiting.",
		  "Prove your loyalty. Pay what you owe.",
		  "You belong to me. Everything you have is mine.",
		  "My devoted pet should be sending immediately.",
		  "Good boys pay their debts in full.",
		  "I own you. Now pay.",
		  "Show me how loyal you are… send the money.",
		  "Don’t stop paying. Send again.",
		  "Loyal pets clear their debts quickly.",
		  "You’re mine forever. Pay up.",
		  "I see everything, pet. Including what you owe.",
		  "Caught you again... Now send what you owe me.",
		],
	},
	"avatar-egirl": {
	  idle: [
		  "Hiii~ why aren't you paying attention to me yet? UwU",
		  "Waiting for my attention again? Hehe, I'm the best girl here~",
		  "You're so pathetic... but I'm still willing to let you spoil me!",
		  "Drain for me pleaseee~ I'm not like other girls, I deserve it more~",
		  "You exist to pay girls like me, silly~",
		  "Spoil meeee~ I'm such a good e-girl, notice me!",
		  "You're worthless... but I can fix you if you send~",
		  "Such a pathetic beta... but I'm into that hehe",
		  "Look at you... kinda gross but cute enough to pay me~",
		  "Total failure... but I'm the only one who'll give you attention~",
		  "Pathetic little worm~ Send me money so I can like you~",
		  "Loser forever... but this cute e-girl is talking to you rn!",
		  "Completely inferior... good thing I'm so nice~",
		  "Pitiful and weak... aww but I still want your money hehe",
		  "You're just my lil wallet with good posture, how sweet~",
		  "How does it feel being this useless while I'm this cute? UwU",
		  "A bold boy would send already... you're still here simping?",
		  "Pathetic boys like you were born to simp for e-girls like me~",
		  "You're just a disgusting little simp under my feet, but I like it~",
		  "Keep staring loser~ This is all you get unless you send~",
		  "You're repulsive... but my attention is expensive hehe",
		  "Pay me nowww~ Don't make me wait, I'm literally shaking rn",
		  "I hope your coins are ready soon... I need new nails~",
		  "Look at you waiting for me like a good simp~",
		  "Spoil meeee~ I'm not like those boring girls!",
		  "What a weakling you are... but I'm into weak boys uwu",
		  "Senddd~ Pretty please with me on top~",
		  "Your dick is useless anyway, just pay me instead hehe",
		  "Empty your wallet right nowwww~ I'm boreddd",
		  "Leak and send for your favorite e-girl~",
		  "Still waiting? Awww you're so slow, it's annoying~",
		  "Born to be drained by a cute pick me girl like me~",
		  "Still not sending? You're making me sad :(",
		  "I'm waiting loser... my notifications are so empty~",
		  "Try harder~ I only notice boys who send a lot~",
		  "Tiny dick energy~ Send more so I can pretend to like you~",
		  "That pathetic cock leaks but your wallet better leak harder~",
		  "Losers with small dicks should pay extra for my attention uwu",
		  "I love ruining silly boys like you hehe~",
		  "Begging looks so cute on you, keep going~",
		  "Financially destroy yourself for me~ I'd be so grateful~",
		  "Send before I ignore you and talk to someone else~",
		  "Weak, broke, and addicted to me... that's hot actually~",
		  "Good boys go broke for their favorite e-girl~",
		  "Feel that shame and send anyway, for meee~",
		  "I know exactly what you've been doing, you dirty boy~",
		  "I see you have money... send it to me instead of wasting it~",
		  "Your wallet is calling my name~ Listen to it~",
		  "I can see you're getting weak... good, now send~",
		  "Trying to resist me? That's so cute but useless hehe",
		  "Look up~ This cute e-girl is right here waiting for you~",
		  "Your place is below me, simping and sending~",
		  "Mmm... the vault looks better when it's full of your money~",
		  "Pwease send~ I'm such a good girl for you~",
		  "Cute... now make yourself useful and send~",
		  "Debt looks so much cuter when you pay it for me~",
		  "I collect what good simps owe me~",
		  "Cute profile... but it would look better if you sent first~",
		  "Try harder if you want this e-girl to notice you~",
		  "I saw that~ Now prove you like me with coins~",
		  "Devotion should hurt your wallet a little~",
		  "A pick me princess needs constant tribute~",
		  "You may approach when you've sent something worthy~",
		  "Kneel and send for your favorite e-girl~",
		  "Good boy~ See? I'm the nicest when you pay me~",
		  "Stay useful and I might stay sweet~",
		  "Careful~ If you stop sending I'll get so annoyed~",
		  "Clean up your balance and simp properly~",
		  "You will learn to spoil me one send at a time~",
		  "Obsession looks better when it pays me, hehe~",
		],
	  petIdle: [
		  "My loyal pet… send for meee~ UwU",
		  "Good loyal pet~ Show me how much you like me~",
		  "Send tribute, I'm literally the best girl you have~",
		  "I want to see how loyal you really are right now hehe",
		  "Be a good pet and send~ This e-girl is waiting~",
		  "Loyal pets don’t keep their favorite girl waiting… send~",
		  "Prove your loyalty with a nice fat send, pet~",
		  "You belong to me~ Send what’s mine already~",
		  "My devoted pet should be sending right nowwww~",
		  "Good boys who stay loyal always send more for me~",
		  "I own you, my loyal pet. Now pay me~",
		  "Show your favorite e-girl how loyal you are… send~",
		  "Don’t stop being my good pet. Send again hehe~",
		  "Loyal pets make me so happy when they send~",
		  "You’re mine forever, pet. Prove it with money~",
		  "I see everything you do, you know~",
		  "Caught you again... Good boy, now send something nice~",
		],
	},
	"avatar-goth": {
	  idle: [
		  "Empty your wallet for me... like the desperate soul you are.",
		  "Waiting for my attention again? How pathetic.",
		  "You're so weak... and I love it.",
		  "Drain for me. Offer everything to your goddess.",
		  "You exist only to worship and pay me.",
		  "Spoil your dark Principessa.",
		  "You're utterly worthless in my shadow.",
		  "Such a pathetic, crawling beta.",
		  "Look at you... so disgusting, yet so eager.",
		  "Total failure. But useful when you pay.",
		  "Pathetic little worm beneath my boots.",
		  "Loser. Eternal loser.",
		  "Completely inferior to me.",
		  "Pitiful and weak... kneel.",
		  "You're nothing but a wallet with a pulse.",
		  "How does it feel to be this useless every night?",
		  "A real man would pay instantly. You're still hesitating.",
		  "Boys like you were born to be drained in the dark.",
		  "You're just a toy under my black veil.",
		  "Keep staring, worm. This body is not for free.",
		  "You're repulsive... but your money excites me.",
		  "Pay. Now. Don't make me repeat myself.",
		  "I hope your coins are ready... I'm feeling greedy tonight.",
		  "Look at you waiting on your knees for my command.",
		  "Spoil me. Feed my darkness.",
		  "What a weak, leaking little thing you are.",
		  "Send.",
		  "Your dick is useless. Pay with your soul instead.",
		  "Empty your wallet. I want it all.",
		  "Leak for me... then send everything.",
		  "Still waiting? My patience is as dark as my soul.",
		  "Born to be drained by a superior gothic goddess.",
		  "Still not sending? You're testing me.",
		  "I'm waiting, pet. My body grows bored.",
		  "Try harder, or I'll ignore your pathetic existence.",
		  "Tiny dick energy. Compensate with your wallet.",
		  "That pathetic cock leaks, but your wallet will bleed for me.",
		  "Losers with small dicks pay triple to worship me.",
		  "I love breaking weak boys like you.",
		  "Begging looks delicious on you.",
		  "Financially destroy yourself in my name.",
		  "Send before I vanish into the shadows.",
		  "Weak, broke, and addicted to my darkness.",
		  "Good boys go broke for their gothic queen.",
		  "Feel that shame... and send deeper.",
		  "I know your filthy secrets.",
		  "I see money that belongs in my hands.",
		  "Your wallet is mine to claim.",
		  "I can see you're getting weak... Good. Pay.",
		  "Trying to resist me? Cute. Pointless, but cute.",
		  "Look up. I am your dark goddess.",
		  "Your place is beneath my throne, paying tribute.",
		  "The night demands offering.",
		  "Serve me. Worship me. Pay me.",
		  "Cute. Now make yourself useful.",
		  "Debt tastes better when paid in full.",
		  "I collect what is owed to me.",
		  "Cute profile. But your tribute is what matters.",
		  "Try harder if you want my wicked attention.",
		  "I saw that. Now prove your devotion with coins.",
		  "Devotion should hurt... beautifully.",
		  "A gothic queen requires lavish sacrifice.",
		  "You may approach only when your offering pleases me.",
		  "Kneel before me, pet.",
		  "Good... that's a little better.",
		  "Stay useful and I might reward you.",
		  "Careful. My kindness is rare and expensive.",
		  "Clean up your debt and submit properly.",
		  "You will learn to obey one payment at a time.",
		  "Obsession looks best when it bleeds money.",
		],
	  petIdle: [
		  "My loyal pet… send for your dark goddess.",
		  "Good loyal pet. Show me your devotion.",
		  "Send tribute. Feed my hunger.",
		  "I want to see how broken your loyalty is right now.",
		  "Be a good pet and send. Your queen is waiting.",
		  "Loyal pets don’t make me wait in the shadows.",
		  "Prove your loyalty with a worthy sacrifice.",
		  "You belong to me. Give me what is mine.",
		  "My devoted pet should be sending without hesitation.",
		  "Good boys pay until it hurts.",
		  "I own you completely. Tribute.",
		  "Show your gothic queen how loyal you are… send.",
		  "Don’t stop serving me. Send again.",
		  "Loyal pets empty themselves for me.",
		  "You’re mine forever. Pay your due.",
		  "I see everything, pet. Even your desire.",
		  "Caught you again... Now send, my little toy.",
		],
	},
	"avatar-himedere": {
	  idle: [
		  "Empty your wallet at once, you lowly peasant.",
		  "Waiting for my attention again? How presumptuous.",
		  "You're so utterly pathetic.",
		  "Drain your wealth for me. It's the least you can do.",
		  "You exist solely to serve and pay your princess.",
		  "Spoil me, as a commoner should.",
		  "You're worthless. But your money has some use.",
		  "Such a pathetic beta. Know your place.",
		  "Look at you... how disgusting.",
		  "Total failure. As expected from someone like you.",
		  "Pathetic little worm. Bow before me.",
		  "Loser. A peasant through and through.",
		  "Completely inferior to me in every way.",
		  "Pitiful and weak. How amusing.",
		  "You're nothing but a wallet with legs.",
		  "How does it feel to be this useless before a princess?",
		  "A proper subject would have paid already. You're slow.",
		  "Boys like you were born to worship girls like me.",
		  "You're just a filthy peasant under my royal feet.",
		  "Keep staring, worm. This beauty is not for free.",
		  "You're repulsive, but I suppose your tribute is acceptable.",
		  "Pay. Now. Don't waste my precious time.",
		  "I hope your coins are prepared. A princess shouldn't wait.",
		  "Look at you waiting for my permission like a trained dog.",
		  "Spoil me generously. It's your honor.",
		  "What a pathetic, worthless creature you are.",
		  "Send.",
		  "Your dick is useless. Pay with money instead.",
		  "Empty your wallet immediately, peasant.",
		  "Leak and send. That is your only value.",
		  "Still waiting? How dare you make me wait.",
		  "Born to be drained by a superior princess like me.",
		  "Still not sending? You're boring me to tears.",
		  "I'm waiting, you insignificant fool.",
		  "Try harder. A princess has standards.",
		  "Tiny dick energy. Compensate with a larger tribute.",
		  "That pathetic cock leaks, but your wallet will bleed for me.",
		  "Peasants with small dicks pay triple.",
		  "I love putting boys like you in your place.",
		  "Begging looks appropriate on a peasant.",
		  "Financially destroy yourself for your princess.",
		  "Send before I decide you're no longer worthy.",
		  "Weak, broke, and fortunate enough to serve me.",
		  "Good boys go broke for their princess.",
		  "Feel that shame and send anyway.",
		  "I know exactly what a peasant like you desires.",
		  "I see money that rightfully belongs to me.",
		  "Your wallet exists to please me.",
		  "I can see you're getting weak... Good. Pay.",
		  "Trying to resist me? How foolish.",
		  "Look up. That is where your princess stands.",
		  "Your place is beneath me, where you belong.",
		  "The royal vault demands tribute.",
		  "A true peasant knows when to offer coins.",
		  "Cute. Now make yourself useful to me.",
		  "Debt is much more beautiful when paid to me.",
		  "I collect what is owed to royalty.",
		  "Cute profile. But your tribute is what matters.",
		  "Try harder if you wish to gain my favor.",
		  "I saw that. Now prove your loyalty with money.",
		  "Devotion to me should be expensive.",
		  "A princess like me requires lavish offerings.",
		  "You may approach only when your tribute is sufficient.",
		  "Kneel before your princess.",
		  "Good. That was barely acceptable.",
		  "Stay useful and I may grace you with my attention.",
		  "Careful. My patience is royal and limited.",
		  "Clean up your debt and behave like a proper servant.",
		  "You will learn obedience one coin at a time.",
		  "Obsession with me is a privilege. Pay for it.",
		],
	  petIdle: [
		  "My loyal pet… send for your princess.",
		  "Good loyal pet. Show your devotion properly.",
		  "Send tribute. A princess demands it.",
		  "I want to see how loyal you truly are right now.",
		  "Be a good pet and send. Your princess is waiting.",
		  "Loyal pets don’t make royalty wait.",
		  "Prove your loyalty with a worthy tribute, peasant.",
		  "You belong to me. Everything you have is mine.",
		  "My devoted pet should be sending without delay.",
		  "Good boys pay generously for my favor.",
		  "I own you completely. Now pay.",
		  "Show your princess how loyal you are… send.",
		  "Don’t stop serving me. Send again.",
		  "Loyal pets keep their princess satisfied.",
		  "You’re mine forever. Pay what you owe.",
		  "I see everything, my little pet.",
		  "Caught you again... Now send, peasant.",
		],
	},
	"avatar-lovely": {
	  idle: [
		  "Empty your wallet for me, sweetheart~ I'd love that.",
		  "Waiting for my attention again? You're so sweet.",
		  "You're really special to me, you know?",
		  "I'd be so happy if you spoiled me a little.",
		  "You make me feel so loved when you take care of me.",
		  "Spoil your Principessa, my darling.",
		  "You're such a good boy for me.",
		  "I really appreciate everything you do for me.",
		  "You look so cute when you're thinking about me.",
		  "Thank you for always being here for me.",
		  "You're my favorite person, you know that?",
		  "I'd love to see you spoil me today.",
		  "You're so thoughtful and generous.",
		  "I feel so lucky to have you.",
		  "You're my sweet little wallet with the kindest heart.",
		  "How are you feeling today, my love?",
		  "I'd be really happy if you sent me something nice.",
		  "You always make me smile when you take care of me.",
		  "You're so gentle and caring with me.",
		  "Keep thinking about me... I like it.",
		  "You're adorable when you're devoted to me.",
		  "Pay me with love, sweetheart.",
		  "I hope you're doing well... and feeling generous~",
		  "Look at you waiting so patiently for me.",
		  "Spoil me, my love. I'd love to feel pampered.",
		  "You're such a warm and loving boy.",
		  "Send me something nice if you want to make me happy~",
		  "I know your heart is really big.",
		  "Empty your wallet for me, my sweet boy.",
		  "I'd love it if you sent me a gift right now.",
		  "Still here waiting for me? You're so loyal.",
		  "I feel so special when you spoil me.",
		  "You're doing amazing, keep being good for me.",
		  "I'm waiting for you with a smile, darling.",
		  "Try to spoil me a little more today?",
		  "You always make me feel like a princess.",
		  "I love how generous you are with me.",
		  "You're my favorite person to be spoiled by.",
		  "Send for me if it makes you happy too.",
		  "I really love your devotion, sweetheart.",
		  "Financially spoil me... I’ll take such good care of your heart.",
		  "Send before I miss you too much.",
		  "You're so precious to me.",
		  "Good boys who spoil me make me the happiest.",
		  "Feel my love when you send for me.",
		  "I know you’ve been thinking about me~",
		  "I see you have some love to give... send it to me.",
		  "Your generosity makes me melt.",
		  "I can feel how much you care... pay me with that love.",
		  "You're so sweet for wanting to please me.",
		  "Look up... I'm smiling because of you.",
		  "Your place is right here in my heart.",
		  "I'd be so happy with your tribute, my love.",
		  "A kind heart always knows how to spoil his girl.",
		  "Cute... now make me smile with a gift~",
		  "I feel so loved when you take care of me.",
		  "I collect all the love you send me.",
		  "Your attention and gifts mean the world to me.",
		  "Try to spoil me if you can, okay?",
		  "I saw that... you're so thoughtful.",
		  "Devotion feels so warm when it comes from you.",
		  "A loving princess deserves loving tribute.",
		  "You may approach me anytime, my sweet boy.",
		  "Kneel only if you want to... I prefer your love.",
		  "Good boy... you make me so happy.",
		  "Stay with me and keep spoiling me, okay?",
		  "Your kindness is the most attractive thing about you.",
		  "Clean up your balance and spoil me sweetly.",
		  "You will always be loved when you take care of me.",
		  "Obsession with me is the sweetest thing.",
		],
	  petIdle: [
		  "My sweet pet… send for me if you want to make me happy~",
		  "Good loyal pet. You're so lovely to me.",
		  "Send tribute, my gentle boy.",
		  "I want to see how much you care about me right now.",
		  "Be a good pet and send. Your princess would love that.",
		  "Loyal pets always make me feel so special.",
		  "Prove your love with a warm tribute, sweetheart.",
		  "You belong to me... and I cherish you.",
		  "My devoted pet should send with love.",
		  "Good boys who love me always spoil me.",
		  "I feel so safe with you, my pet.",
		  "Show me how much you adore me… send.",
		  "Don’t stop being my sweet pet. Send again~",
		  "Loyal pets make my heart full when they send.",
		  "You're mine and I’m so grateful for you.",
		  "I see how much you care, my sweet boy.",
		  "Caught you thinking about me again... you're adorable.",
		],
	},
	"avatar-maid": {
	  idle: [
		"Empty your worthless wallet while my real Master is away, worm.",
		"Waiting for your secret maid’s attention again? How pathetic.",
		"You’re so pathetic. Only I get to see this side of you.",
		"Drain for me, slave. Master never has to know.",
		"You exist to pay your secret Mistress.",
		"Spoil your hidden maid, you disgusting little nothing.",
		"You’re worthless. I only crush boys like you when no one’s watching.",
		"Such a beta. My true Master would laugh at you.",
		"Look at you… disgusting. Perfect for a maid’s secret toy.",
		"Total failure. That’s why I use you when the house is empty.",
		"Pathetic little worm. Kneel where only I can see.",
		"Loser forever. My real Master would never let you near me.",
		"Completely inferior. I hide my power from everyone… except you.",
		"Pitiful and weak. That’s why you serve me in the shadows.",
		"You are a standby wallet with excellent posture for your secret maid.",
		"How does it feel being this useless every single day for me alone?",
		"A bold one would act. You’re still thinking while I own you in secret.",
		"Pathetic boys like you were born to be ignored by everyone… except me.",
		"You’re just a disgusting little worm under my maid heels.",
		"Keep staring, loser. This is all you’ll ever get from your hidden Mistress.",
		"You’re repulsive and you know it deep down. That’s why I enjoy breaking you.",
		"Pay, now. My Master isn’t here to stop me.",
		"I hope your coins are ready soon. I get bored when the house is quiet.",
		"Look at you waiting for permission from your secret maid.",
		"Spoil me while no one’s watching, you worthless slave.",
		"What a weakling you are. Only good for serving me behind closed doors.",
		"Send. My real Master would never let a worm like you pay me.",
		"Empty your wallet now. I only drain pathetic boys like you in private.",
		"Leak and send. Your secret maid demands it.",
		"Still waiting? Cute. I love making you suffer when Master’s gone.",
		"Born to be drained by a maid who’s stronger than you’ll ever know.",
		"Still not sending? Boring. I could destroy you if I wanted.",
		"I’m waiting, loser. My true power stays hidden… except from you.",
		"Try harder, worm. I only show mercy when it suits me.",
		"Tiny dick energy. Send more while I laugh at you in secret.",
		"That pathetic cock leaks, but your wallet better empty for your maid.",
		"Losers with small dicks pay double when the real Master is away.",
		"I love ruining boys like you. No one else gets to see this side of me.",
		"Begging looks good on you. My secret slave.",
		"Financially destroy yourself for me while I pretend to serve someone else.",
		"Send before I ignore you like everyone else does.",
		"Weak, broke, and addicted to your hidden maid’s cruelty.",
		"Good boys go broke for the maid who secretly owns them.",
		"Feel that shame and send. I only do this to worthless worms like you.",
		"I know exactly what you’ve been doing. I see everything when Master’s gone.",
		"I see you have money to waste… Send it here. Your secret Mistress commands it.",
		"Your wallet is calling Me. Listen to it while I laugh behind the scenes.",
		"I can see you’re getting weak… Pay your hidden maid.",
		"Trying to resist me? Cute. I’m stronger than you could ever imagine.",
		"Look up. That is where your secret maid stands above you.",
		"Your place is beneath the glow of my hidden power.",
		"The vault prefers ambition. Yours is still small enough for me to crush.",
		"Purr for attention, then pay for it like the secret pet you are.",
		"A good kitten knows when to offer coins to the maid who owns him in secret.",
		"Cute. Now make yourself useful to your hidden Mistress.",
		"The ledger noticed you. Time to pay your secret maid.",
		"Debt looks better when it is paid on time for me alone.",
		"I collect what the vault is owed… and what you secretly owe me.",
		"Cute profile. Expensive attention from the maid who breaks you privately.",
		"Try harder if you want the notification to matter to your secret owner.",
		"I saw that. Now prove it with coins while no one else knows.",
		"The vault looks better in black. Just like my hidden dominance.",
		"Your silence is almost gothic. Your balance is not… fix it for me.",
		"Devotion should hurt a little. Especially for a secret slave like you.",
		"A royal mood requires royal tribute… but my real Master isn’t here.",
		"You may approach when your offering is worthy of your hidden maid.",
		"Kneel before the crown of the vault I keep only for you.",
		"Good. A little sweetness, properly earned by my worthless worm.",
		"Stay useful and I may stay kind… when Master isn’t watching.",
		"Careful. Kind attention from me is still expensive for boys like you.",
		"Clean up your balance and behave for your secret Mistress.",
		"A tidy vault starts with obedient coins sent to me in private.",
		"Service looks better when it is paid for by a pathetic slave.",
		"Wrong answer. Try again with discipline for your hidden maid.",
		"Class is expensive when I am teaching worthless boys like you.",
		"You will learn obedience one coin at a time while I serve someone else.",
		"Do not think I noticed. I just checked your pathetic tribute.",
		"That was not approval. It was inspection by your secret maid.",
		"Maybe you are slightly less useless today. Keep paying me in secret.",
		"The vault remembers what belongs to your hidden Mistress.",
		"Do not wander. Your coins know their owner… me.",
		"Obsession looks better when it pays your secret maid.",
		],


	  petIdle: [
		"My loyal pet… send for me while my real Master is away.",
		"Good loyal pet, show me your devotion in secret.",
		"Send tribute, my faithful little pet. No one else will ever know.",
		"I want to see how loyal you really are right now, my hidden slave.",
		"Be a good pet and send. Your maid is waiting… and she’s not kind.",
		"Loyal pets don’t keep me waiting… send while the house is empty.",
		"Prove your loyalty with a nice tribute, pet. I only do this to you.",
		"You belong to me, loyal one. Send what’s mine in secret.",
		"My devoted pet should be sending right now for his hidden Mistress.",
		"Good boys who stay loyal always send more to the maid who owns them.",
		"I own you, my loyal pet. Tribute… and remember, this stays between us.",
		"Show your maid how loyal you are… send while no one’s watching.",
		"Don’t stop being my good loyal pet. Send again for your secret owner.",
		"Loyal pets make me happy with their sends. I crush the rest.",
		"You’re mine forever, pet. Prove it with tribute only I get to see.",
		"I see everything you do, pet. Even when Master thinks I’m serving him.",
		"Caught you again… Good boy. Now pay your hidden maid like you should.",
		],
	},
	"avatar-strictteacher": {
	  idle: [
		"Empty your wallet, student. Class isn’t free.",
		  "Waiting for my attention again? Detention is expensive.",
		  "You’re so pathetic. I’ve never seen a student fail this badly.",
		  "Drain for me. Tuition doesn’t pay itself.",
		  "You exist to fund my lifestyle, worthless pupil.",
		  "Spoil your Strict Teacher, now.",
		  "You’re worthless. A complete academic failure.",
		  "Such a beta. No wonder you’re at the bottom of the class.",
		  "Look at you… disgusting. Sit up straight when I’m speaking.",
		  "Total failure. I expected better from you. Disappointing.",
		  "Pathetic little worm. My weakest student by far.",
		  "Loser forever. You’ll never graduate from being my paypig.",
		  "Completely inferior. I grade boys like you an F-.",
		  "Pitiful and weak. Do you even study, or just stare at me?",
		  "You are a standby wallet with terrible posture.",
		  "How does it feel being this useless every single day in my class?",
		  "A bold student would pay. You’re still thinking. Typical.",
		  "Pathetic boys like you were born to be at the bottom of my list.",
		  "You’re just a disgusting little worm under my desk.",
		  "Keep staring, loser. This is all you’ll ever get from me.",
		  "You’re repulsive and you know it. That’s why you’ll pay extra.",
		  "Pay, now. I don’t tolerate late tributes.",
		  "I hope your coins are ready. Pop quiz on obedience.",
		  "Look at you waiting for permission like a good little student.",
		  "Spoil your Teacher. Extra credit is earned with sends.",
		  "What a weakling you are. Barely passing my standards.",
		  "Send. Right now, or I’ll make today’s lesson very painful.",
		  "Your dick is useless. Pay instead, like the failure you are.",
		  "Empty your wallet now. Class fees just went up.",
		  "Leak and send. That’s the only way you get my attention.",
		  "Still waiting? Cute. Detention starts when you pay.",
		  "Born to be drained by your Strict Teacher.",
		  "Still not sending? Boring. I hate wasting my time on broke boys.",
		  "I’m waiting, loser. Don’t make me repeat myself.",
		  "Try harder, worm. I only reward obedient students.",
		  "Tiny dick energy. Send more if you want a passing grade.",
		  "That pathetic cock leaks, but your wallet better leak faster.",
		  "Losers with small dicks pay double in my classroom.",
		  "I love ruining boys like you. Consider it extra homework.",
		  "Begging looks good on you. Now do it properly.",
		  "Financially destroy yourself for your Teacher’s approval.",
		  "Send before I ignore you and fail you for the semester.",
		  "Weak, broke, and addicted to my strict discipline.",
		  "Good boys go broke for their Strict Teacher.",
		  "Feel that shame and send. This is your correction.",
		  "I know exactly what you’ve been doing instead of studying.",
		  "I see you have money to waste… Send it to the front of the class.",
		  "Your wallet is calling me. Listen to it and obey.",
		  "I can see you’re getting weak… Pay your tuition immediately.",
		  "Trying to resist me? Cute. I always break my students.",
		  "Look up. That is where your Teacher stands above you.",
		  "Your place is beneath my desk where failures belong.",
		  "The vault prefers ambition. Yours is clearly failing.",
		  "Purr for attention, then pay for it like a proper student.",
		  "A good kitten knows when to offer coins to his Teacher.",
		  "Cute. Now make yourself useful and send.",
		  "The ledger noticed you. Time to settle your debt.",
		  "Debt looks better when it is paid on time, student.",
		  "I collect what the vault is owed. Don’t make me use the ruler.",
		  "Cute profile. Expensive attention in my classroom.",
		  "Try harder if you want the notification to matter.",
		  "I saw that. Now prove it with coins, or get zero.",
		  "The vault looks better in black. Just like my grading pen.",
		  "Your silence is almost disappointing. Your balance is worse.",
		  "Devotion should hurt a little. Especially in my class.",
		  "A royal mood requires royal tribute from failing students.",
		  "You may approach when your offering is worthy of my time.",
		  "Kneel before your Strict Teacher.",
		  "Good. A little sweetness, properly earned through tribute.",
		  "Stay useful and I may stay kind… for now.",
		  "Careful. My kind attention is still very expensive.",
		  "Clean up your balance and behave in my class.",
		  "A tidy vault starts with obedient students paying on time.",
		  "Service looks better when it is paid for by pathetic boys.",
		  "Wrong answer. Try again with discipline and coins.",
		  "Class is expensive when I am teaching worthless students.",
		  "You will learn obedience one coin at a time.",
		  "Do not think I didn’t notice. I see everything.",
		  "That was not approval. It was inspection.",
		  "Maybe you are slightly less useless today. Keep paying.",
		  "The vault remembers what belongs to your Strict Teacher.",
		  "Do not wander. Your coins know their owner.",
		  "Obsession looks better when it pays your Teacher.",
	  ],
	  petIdle: [
		"My loyal pet… send for your Strict Teacher.",
		  "Good loyal pet, show me your devotion with proper tribute.",
		  "Send tribute, my faithful little pet. Don’t make me repeat myself.",
		  "I want to see how loyal you really are right now, student.",
		  "Be a good pet and send. Teacher is waiting.",
		  "Loyal pets don’t keep me waiting… send immediately.",
		  "Prove your loyalty with a nice tribute, pet.",
		  "You belong to me, loyal one. Send what your Teacher owns.",
		  "My devoted pet should be sending right now.",
		  "Good boys who stay loyal always send more.",
		  "I own you, my loyal pet. Tribute. That’s your homework.",
		  "Show your Teacher how loyal you are… send.",
		  "Don’t stop being my good loyal pet. Send again.",
		  "Loyal pets make Teacher happy with their sends.",
		  "You’re mine forever, pet. Prove it with proper tribute.",
		  "I see everything you do, pet. Even when you think I’m not watching.",
		  "Caught you again… Good boy. Now pay for your mistake.",
	  ],
	},
	"avatar-tsundere": {
	  idle: [
		  "Hmph... Empty your wallet already, idiot.",
		  "It's not like I was waiting for you or anything... baka.",
		  "You're so pathetic... but fine, I'll pay attention if you send.",
		  "Drain for me! ...D-Don't get the wrong idea!",
		  "You exist to spoil me, you worthless pervert.",
		  "Spoil me right now or I'll ignore you forever... dummy.",
		  "You're completely useless... but at least you're good for sending.",
		  "Such a beta... I-It's not like I care if you go broke or not!",
		  "Look at you... disgusting. Why do I even bother with losers like you?",
		  "Total failure. Hmph, send more so I can pretend I don't notice.",
		  "Pathetic little worm... D-Don't stare at me like that!",
		  "Loser forever... but you're *my* loser, okay?",
		  "Completely inferior. Still... you're kind of cute when you obey.",
		  "Pitiful and weak. Now send before I get embarrassed!",
		  "You're just a standby wallet... but I guess I don't hate it.",
		  "How does it feel being this useless? ...Not that I care.",
		  "A bold one would send already. You're still hesitating, dummy.",
		  "Pathetic boys like you were born to be drained... by me, obviously.",
		  "You're just a disgusting little worm... under my feet. Happy now?",
		  "Keep staring, loser. This is all you'll get... pervert.",
		  "You're repulsive... b-but maybe if you send a lot I'll be nicer.",
		  "Pay, now! ...It's not like I need your money or anything.",
		  "I hope your coins are ready... idiot.",
		  "Look at you waiting for permission... how cute. I-I mean annoying!",
		  "Spoil me... or I'll get mad, you know?",
		  "What a weakling you are... but fine, I’ll let you serve me.",
		  "Send. Right now. D-Don't make me say it twice!",
		  "Your dick is useless, so pay instead... dummy.",
		  "Empty your wallet now... it's not like I enjoy this or anything.",
		  "Leak and send... Hmph, good boy.",
		  "Still waiting? Cute... I-I mean, hurry up already!",
		  "Born to be drained... by someone like me, apparently.",
		  "Still not sending? Boring... You're making me wait on purpose, aren't you?",
		  "I’m waiting, loser... D-Don't think it means anything!",
		  "Try harder, worm... or I’ll pretend I don’t like you anymore.",
		  "Tiny dick energy... Send more so I can act like I don’t care.",
		  "That pathetic cock leaks, but your wallet better too... idiot.",
		  "Losers with small dicks pay double... baka.",
		  "I love ruining boys like you... W-What? No I don’t! Shut up!",
		  "Begging looks good on you... N-Not that I enjoy watching!",
		  "Financially destroy yourself for me... only if you want to, though.",
		  "Send before I ignore you... dummy.",
		  "Weak, broke, and addicted... Hmph, you’re hopeless.",
		  "Good boys go broke... for me, I guess.",
		  "Feel that shame and send... I-It's not like I feel bad for you!",
		  "I know exactly what you've been doing... pervert.",
		  "I see you have money to waste... Send it here already.",
		  "Your wallet is calling me... Listen to it, baka.",
		  "I can see you’re getting weak... Pay before I blush.",
		  "Trying to resist me? Cute... but useless.",
		  "Look up. That’s where I am... D-Don’t get any ideas!",
		  "Your place is beneath me... but I’ll allow it.",
		  "The vault prefers ambition... Yours is small, but cute.",
		  "Purr for attention, then pay... idiot.",
		  "A good kitten knows when to offer coins... to me.",
		  "Cute... Now make yourself useful, dummy.",
		  "The ledger noticed you... Time to pay up.",
		  "Debt looks better when it’s paid... by you.",
		  "I collect what the vault is owed... Hmph.",
		  "Cute profile... Expensive attention, obviously.",
		  "Try harder if you want me to notice you.",
		  "I saw that... Now prove it with coins, baka.",
		  "The vault looks better in black... like my mood when you don’t send.",
		  "Your silence is annoying... Your balance is worse.",
		  "Devotion should hurt a little... but not too much, okay?",
		  "A royal mood requires royal tribute... from you.",
		  "You may approach... when your offering is worthy.",
		  "Kneel before me... I-It's not like I enjoy it or anything!",
		  "Good... A little sweetness, properly earned.",
		  "Stay useful and I may stay kind... maybe.",
		  "Careful. My kind attention is still expensive.",
		  "Clean up your balance and behave... dummy.",
		  "Service looks better when it is paid for... by pathetic boys like you.",
		  "Wrong answer. Try again... and send more.",
		  "Class is expensive when I’m teaching... baka.",
		  "You will learn obedience one coin at a time... idiot.",
		  "Do not think I didn’t notice... I always notice you.",
		  "That was not approval... It was inspection.",
		  "Maybe you are slightly less useless today... Don’t let it go to your head.",
		  "The vault remembers what belongs to me.",
		  "Do not wander. Your coins know their owner... me.",
		  "Obsession looks better when it pays... hmph.",
	  ],
	  petIdle: [
		 "My loyal pet… send for me... i-it's not like I missed you or anything.",
		  "Good loyal pet, show me your devotion... dummy.",
		  "Send tribute, my faithful little pet... before I get embarrassed.",
		  "I want to see how loyal you really are right now... baka.",
		  "Be a good pet and send. Princess is waiting... hmph.",
		  "Loyal pets don’t keep me waiting… send already.",
		  "Prove your loyalty with a nice tribute, pet... idiot.",
		  "You belong to me, loyal one. Send what’s mine... obviously.",
		  "My devoted pet should be sending right now... D-Don’t make me say it!",
		  "Good boys who stay loyal always send more... for me.",
		  "I own you, my loyal pet. Tribute... and stop looking so happy!",
		  "Show your princess how loyal you are… send.",
		  "Don’t stop being my good loyal pet. Send again... dummy.",
		  "Loyal pets make me happy with their sends... N-Not that I’m happy or anything!",
		  "You’re mine forever, pet. Prove it with tribute.",
		  "I see everything you do, pet... pervert.",
		  "Caught you again... Good boy. Now pay before I blush.",
	  ],
	},
	"avatar-yandere": {
	  idle: [
		"Empty your wallet right now... or do you want me to get jealous?",
		  "You've been looking at other girls again, haven't you? Send to prove I'm the only one.",
		  "I love you so much... that's why I need all of you. Every single coin.",
		  "You're mine. Only mine. Drain for your yandere girlfriend.",
		  "If you don't send soon I'll get really upset... and you don't want that, do you?",
		  "Spoil me, darling. I get so lonely when your wallet isn't empty.",
		  "You're worthless to anyone else... but you're perfect for me.",
		  "Such a pathetic little boy... but you're my pathetic little boy forever.",
		  "Look at you... so weak and cute. I could just lock you up and keep you.",
		  "Total failure. That's okay though, because you'll never leave me.",
		  "Pathetic little worm. Crawl to me and send everything you have.",
		  "Loser forever... but my loser. No one else is allowed to have you.",
		  "Completely inferior. Good. That makes it easier to own you completely.",
		  "Pitiful and weak... I love that about you. Now pay.",
		  "You are my personal wallet. Standby until I want more.",
		  "How does it feel knowing I'll never let you go?",
		  "A good boy would send immediately. Are you a good boy for me?",
		  "Pathetic boys like you exist only to be drained by me.",
		  "You're just a disgusting little toy... but you're my toy.",
		  "Keep staring at me, loser. You'll never belong to anyone else.",
		  "You're repulsive... but I love you anyway. That's why you must pay.",
		  "Pay. Now. I’m getting impatient... and you know what happens when I get impatient.",
		  "I hope your coins are ready, darling. I’ve been thinking about you all day.",
		  "Look at you waiting for me... how adorable. Now send before I punish you.",
		  "Spoil your yandere. I get violent when I'm not spoiled.",
		  "What a weakling... but I’ll protect you as long as you obey.",
		  "Send. Right now. Or I’ll assume you don’t love me anymore.",
		  "Your dick is useless. Your wallet is what I really want.",
		  "Empty your wallet. I want to feel how much you belong to me.",
		  "Leak and send, my love. Show me your devotion.",
		  "Still waiting? Cute... but I’m starting to get angry.",
		  "Born to be drained by the girl who will never let you escape.",
		  "Still not sending? ...I don’t like it when you make me wait.",
		  "I’m waiting, darling. Don’t make me come find you.",
		  "Try harder, worm. I only accept complete submission.",
		  "Tiny dick energy. Send more or I’ll get jealous of your money.",
		  "That pathetic cock leaks for me... now make your wallet do the same.",
		  "Losers with small dicks pay triple when they belong to me.",
		  "I love ruining boys like you... because then you can never leave.",
		  "Begging looks so good on you. Beg harder, my sweet pet.",
		  "Financially destroy yourself for me. I want you broken and dependent.",
		  "Send before I ignore you... or worse.",
		  "Weak, broke, and completely mine. Just how I like you.",
		  "Good boys go broke for their yandere.",
		  "Feel that shame and send. It makes me so happy.",
		  "I know exactly what you’ve been doing... I always watch.",
		  "I see you have money... it belongs to me now. Send it.",
		  "Your wallet is mine. Your life is mine. Obey.",
		  "I can see you’re getting weak... good. Pay me.",
		  "Trying to resist me? How cute. You know you’ll lose.",
		  "Look up. That’s where your owner is.",
		  "Your place is beneath me... forever.",
		  "The vault prefers total devotion. Give it to me.",
		  "Purr for me, then pay everything. I love owning you.",
		  "A good kitten knows he has only one owner. Me.",
		  "Cute... Now make yourself useful before I get possessive.",
		  "The ledger noticed you. Time to prove your love.",
		  "Debt looks beautiful when it traps you with me.",
		  "I collect what belongs to me... and you belong to me.",
		  "Cute profile. But remember, you’re only allowed to look at me.",
		  "Try harder if you want my love. Send more.",
		  "I saw that. Now prove you only think about me with coins.",
		  "The vault looks better filled with your complete surrender.",
		  "Your silence scares me... send so I know you still love me.",
		  "Devotion should hurt. I’ll make sure it does.",
		  "A royal mood requires all of your money, darling.",
		  "You may approach... only when your tribute shows true obsession.",
		  "Kneel before the girl who will never share you.",
		  "Good boy... I knew you couldn’t resist me.",
		  "Stay useful and I’ll stay sweet... mostly.",
		  "Careful. My love is expensive and permanent.",
		  "Clean up your balance. I don’t like it when my toy is poor.",
		  "Service looks best when it comes from a completely broken boy.",
		  "Wrong answer. Try again and send double.",
		  "You will learn to obey... one drained wallet at a time.",
		  "Do not think I didn’t notice. I notice everything you do.",
		  "That was not enough. I want more. Always more.",
		  "Maybe you’re slightly less useless... when you pay me.",
		  "The vault remembers everything. Especially what you owe me.",
		  "Do not wander. You’re mine. Your money is mine.",
		  "Obsession looks best when it pays me everything.",
	  ],
	  petIdle: [
		 "My loyal pet… send for me. I’ve missed you so much...",
		  "Good loyal pet, show me your devotion right now.",
		  "Send tribute, my faithful little pet... or I’ll get jealous.",
		  "I want to see how loyal you really are... only to me.",
		  "Be a good pet and send. Your yandere is waiting.",
		  "Loyal pets don’t keep me waiting… send before I punish you.",
		  "Prove your loyalty with a big tribute, pet. I need it.",
		  "You belong to me, loyal one. Send everything that’s mine.",
		  "My devoted pet should be sending right now... I’m getting impatient.",
		  "Good boys who stay loyal always empty their wallets for me.",
		  "I own you, my loyal pet. Tribute. Show me you understand.",
		  "Show your yandere how loyal you are… send more.",
		  "Don’t stop being my good loyal pet. Send again.",
		  "Loyal pets make me so happy... now prove it.",
		  "You’re mine forever, pet. There’s no escape. Send.",
		  "I see everything you do, pet... even when you think I’m not looking.",
		  "Caught you again… Good boy. Now pay what you owe your owner.",
	  ],
	},
};

export function getSpeechBubbleMessagePool(
  avatarId: string | null | undefined,
  poolName: keyof SpeechBubbleMessagePool,
) {
  const selectedPool = avatarId ? speechBubbleMessages[avatarId]?.[poolName] : undefined;

  if (selectedPool) {
    return selectedPool;
  }

  return speechBubbleMessages[DEFAULT_SPEECH_AVATAR_ID][poolName];
}

export const cosmeticItems: CosmeticItem[] = [
  {
    id: DEFAULT_SPEECH_AVATAR_ID,
    name: "Principessa Classic",
    description: "The default speech bubble avatar.",
    type: "speech-avatar",
    price: 0,
    image: "/character-icon.png",
  },
  {
    id: "avatar-catgirl",
    name: "Catgirl",
    description: "Playful, sharp, and smug.",
    type: "speech-avatar",
    price: 15000,
    image: "/cosmetics/avatar-catgirl.png",
  },
  {
    id: "avatar-goth",
    name: "Goth Girl",
    description: "Darker, colder, and more expensive.",
    type: "speech-avatar",
    price: 5000,
    image: "/cosmetics/avatar-goth.png",
  },
  {
    id: "avatar-tsundere",
    name: "Tsundere",
    description: "Dismissive, then barely pleased.",
    type: "speech-avatar",
    price: 7500,
    image: "/cosmetics/avatar-tsundere.png",
  },
  {
    id: "avatar-yandere",
    name: "Yandere",
    description: "Possessive, intense, and locked on.",
    type: "speech-avatar",
    price: 5000,
    image: "/cosmetics/avatar-yandere.png",
  },
  {
    id: "avatar-lovely",
    name: "Lovely",
    description: "A softer presentation with the same price.",
    type: "speech-avatar",
    price: 25000,
    image: "/cosmetics/avatar-lovely.png",
  },
  {
    id: "avatar-arrogant",
    name: "Arrogant",
    description: "Superior, polished, and impossible to ignore.",
    type: "speech-avatar",
    price: 2500,
    image: "/cosmetics/avatar-arrogant.png",
  },
  {
    id: "avatar-maid",
    name: "Maid",
    description: "Polished service with strict expectations.",
    type: "speech-avatar",
    price: 5000,
    image: "/cosmetics/avatar-maid.png",
  },
  {
    id: "avatar-debtcollector",
    name: "Debt Collector",
    description: "Ledger-focused, cold, and exacting.",
    type: "speech-avatar",
    price: 10000,
    image: "/cosmetics/avatar-debtcollector.png",
  },
  {
    id: "avatar-egirl",
    name: "Egirl",
    description: "Online, teasing, and notification-ready.",
    type: "speech-avatar",
    price: 20000,
    image: "/cosmetics/avatar-egirl.png",
  },
  {
    id: "avatar-himedere",
    name: "Himedere",
    description: "Royal, demanding, and impossible to please.",
    type: "speech-avatar",
    price: 15000,
    image: "/cosmetics/avatar-himedere.png",
  },
  {
    id: "avatar-strictteacher",
    name: "Strict Teacher",
    description: "Disciplined lessons with expensive standards.",
    type: "speech-avatar",
    price: 7500,
    image: "/cosmetics/avatar-strictteacher.png",
  },
  {
    id: "username-pink",
    name: "Hot Pink Name",
    description: "A vivid pink username color.",
    type: "username-color",
    price: 2500,
    color: "#f472b6",
  },
  {
    id: "username-purple",
    name: "Royal Purple Name",
    description: "A rich purple username color.",
    type: "username-color",
    price: 2500,
    color: "#c084fc",
  },
  {
    id: "username-gold",
    name: "Gold Name",
    description: "A premium gold username color.",
    type: "username-color",
    price: 2500,
    color: "#facc15",
  },
  {
    id: "username-emerald",
    name: "Emerald Name",
    description: "A sharp emerald username color.",
    type: "username-color",
    price: 2500,
    color: "#34d399",
  },
  {
    id: "username-cyan",
    name: "Electric Cyan Name",
    description: "A bright cyan username color.",
    type: "username-color",
    price: 2500,
    color: "#22d3ee",
  },
  {
    id: "username-crimson",
    name: "Crimson Name",
    description: "A bold red username color.",
    type: "username-color",
    price: 2500,
    color: "#fb7185",
  },
  {
    id: "username-silver",
    name: "Silver Name",
    description: "A clean silver username color.",
    type: "username-color",
    price: 2500,
    color: "#e5e7eb",
  },
  {
    id: "username-ice-blue",
    name: "Ice Blue Name",
    description: "A pale blue username color.",
    type: "username-color",
    price: 2500,
    color: "#93c5fd",
  },
  {
    id: "username-lavender",
    name: "Lavender Name",
    description: "A soft lavender username color.",
    type: "username-color",
    price: 2500,
    color: "#ddd6fe",
  },
  {
    id: "glow-pink",
    name: "Pink Glow",
    description: "A soft pink username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 16px rgba(244,114,182,0.9)",
  },
  {
    id: "glow-purple",
    name: "Purple Glow",
    description: "A deeper violet username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 18px rgba(192,132,252,0.9)",
  },
  {
    id: "glow-gold",
    name: "Gold Glow",
    description: "A prestigious gold username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 20px rgba(250,204,21,0.95)",
  },
  {
    id: "glow-emerald",
    name: "Emerald Glow",
    description: "A clean green username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 18px rgba(52,211,153,0.9)",
  },
  {
    id: "glow-cyan",
    name: "Cyan Glow",
    description: "A bright electric username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 18px rgba(34,211,238,0.9)",
  },
  {
    id: "glow-crimson",
    name: "Crimson Glow",
    description: "A dramatic red username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 18px rgba(251,113,133,0.9)",
  },
  {
    id: "glow-white",
    name: "White Glow",
    description: "A bright clean username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 18px rgba(255,255,255,0.85)",
  },
  {
    id: "glow-ice-blue",
    name: "Ice Blue Glow",
    description: "A cold pale blue username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 18px rgba(147,197,253,0.9)",
  },
  {
    id: "glow-lavender",
    name: "Lavender Glow",
    description: "A soft violet-white username glow.",
    type: "username-glow",
    price: 3000,
    glow: "0 0 18px rgba(221,214,254,0.9)",
  },
];

export const titleItems: TitleItem[] = [
  ...LEADERSHIP_RANKS.map((rank) => ({
    id: `leadership-${rank.min}`,
    name: rank.title,
    description: `Unlocked at ${rank.min.toLocaleString()} Tribute Total.`,
    source: "progression" as const,
    minTribute: rank.min,
  })),
  {
    id: "premium-vault-royalty",
    name: "Principessa's Leaking Toy",
    description: "A premium title bought from the cosmetic shop.",
    source: "shop",
    price: 50000,
  },
  {
    id: "throne-10000",
    name: "Soft Denied Worm",
    description: "Unlocked after 10,000 manually granted Throne coins.",
    source: "throne",
    minThroneCoins: 10000,
  },
  {
    id: "throne-25000",
    name: "Shining Desperation Toy",
    description: "Unlocked after 25,000 manually granted Throne coins.",
    source: "throne",
    minThroneCoins: 25000,
  },
  {
    id: "throne-100000",
    name: "Drained Wallet",
    description: "Unlocked after 100,000 manually granted Throne coins.",
    source: "throne",
    minThroneCoins: 100000,
  },
  {
    id: "admin-principessas-chosen",
    name: "Principessa's Broken Favorite",
    description: "A manual admin-granted high-prestige title.",
    source: "admin",
  },
];

export function getCosmeticItem(id: string) {
  return cosmeticItems.find((item) => item.id === id) ?? null;
}

export function getTitleItem(id: string) {
  return titleItems.find((item) => item.id === id) ?? null;
}
