export type ProfileBorderStyle =
  | "solid"
  | "split-diagonal"
  | "split-vertical"
  | "tricolor-band"
  | "tricolor-diagonal"
  | "pinstripe"
  | "edge-stripe"
  | "stadium-glow"
  | "conic-slice";

export type ProfileBorderCatalogItem = {
  id: string;
  name: string;
  description: string;
  type: "profile-border";
  price: number;
  color: string;
  borderPalette: [string, string, string?];
  borderStyle: ProfileBorderStyle;
  isArchived?: boolean;
};

function footballBorder(
  item: Omit<ProfileBorderCatalogItem, "type">,
): ProfileBorderCatalogItem {
  return {
    ...item,
    type: "profile-border",
  };
}

export const footballInspiredRotatingBorders: ProfileBorderCatalogItem[] = [
  footballBorder({
    id: "profile-border-rotating-skyline-current",
    name: "Skyline Current Border",
    description: "A sky-blue and white diagonal frame with late-match floodlight energy.",
    price: 21800,
    color: "#6cabdd",
    borderPalette: ["#6cabdd", "#ffffff", "#dbeafe"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-scarlet-marble",
    name: "Scarlet Marble Border",
    description: "A sharp red-and-white frame with a gold center line for louder contrast.",
    price: 22200,
    color: "#d90429",
    borderPalette: ["#d90429", "#ffffff", "#fcd34d"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-harbor-ember",
    name: "Harbor Ember Border",
    description: "A deep ember-red frame with cream highlights and darker corners.",
    price: 22400,
    color: "#c1121f",
    borderPalette: ["#c1121f", "#fff1f2", "#111827"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-regent-blue",
    name: "Regent Blue Border",
    description: "A royal blue split frame with colder white and cobalt edges.",
    price: 22100,
    color: "#034694",
    borderPalette: ["#034694", "#ffffff", "#60a5fa"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-crimson-forge",
    name: "Crimson Forge Border",
    description: "A hot red frame tempered with darker metal and warm gold trim.",
    price: 22800,
    color: "#da291c",
    borderPalette: ["#da291c", "#fbbf24", "#111827"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-midnight-lane",
    name: "Midnight Lane Border",
    description: "A navy pinstripe frame softened by clean white and pale blue breaks.",
    price: 21900,
    color: "#132257",
    borderPalette: ["#132257", "#ffffff", "#93c5fd"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-signal-dawn",
    name: "Signal Dawn Border",
    description: "A high-contrast yellow-black frame cut with warmer amber highlights.",
    price: 22300,
    color: "#facc15",
    borderPalette: ["#facc15", "#111827", "#fde68a"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-alpine-regal",
    name: "Alpine Regal Border",
    description: "A ceremonial red-white-blue frame with a cleaner diagonal sweep.",
    price: 22900,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#ffffff", "#1d4ed8"],
    borderStyle: "tricolor-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-frosted-capital",
    name: "Frosted Capital Border",
    description: "A cooler blue-white border with darker capital-night depth.",
    price: 22000,
    color: "#1d4ed8",
    borderPalette: ["#1d4ed8", "#ffffff", "#0f172a"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-neon-charge",
    name: "Neon Charge Border",
    description: "A red-white-cobalt slice frame that feels fast and electric.",
    price: 22700,
    color: "#ef4444",
    borderPalette: ["#ef4444", "#ffffff", "#2563eb"],
    borderStyle: "conic-slice",
  }),
  footballBorder({
    id: "profile-border-rotating-iron-borough",
    name: "Iron Borough Border",
    description: "A darker red frame with amber accents and pale stand-light trim.",
    price: 22500,
    color: "#b91c1c",
    borderPalette: ["#b91c1c", "#f59e0b", "#fff7ed"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-midnight-tidal",
    name: "Midnight Tidal Border",
    description: "A blue-black pinstripe border finished with small gold flashes.",
    price: 23000,
    color: "#1d4ed8",
    borderPalette: ["#1d4ed8", "#111827", "#facc15"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-rosso-onyx",
    name: "Rosso Onyx Border",
    description: "A red-and-black pinstripe frame sharpened by colder white contrast.",
    price: 23000,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#111827", "#ffffff"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-azure-halo",
    name: "Azure Halo Border",
    description: "A bright blue glow frame with clean white and deeper sapphire edges.",
    price: 22100,
    color: "#38bdf8",
    borderPalette: ["#38bdf8", "#ffffff", "#1d4ed8"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-ivory-obsidian",
    name: "Ivory Obsidian Border",
    description: "A black-and-white split border with colder silver polish.",
    price: 22400,
    color: "#f8fafc",
    borderPalette: ["#f8fafc", "#111827", "#cbd5e1"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-imperial-garnet",
    name: "Imperial Garnet Border",
    description: "A darker garnet frame with amber warmth and pale ceremonial light.",
    price: 22600,
    color: "#7f1d1d",
    borderPalette: ["#7f1d1d", "#d97706", "#fff7ed"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-storm-current",
    name: "Storm Current Border",
    description: "A blue-black diagonal frame cut by lighter sky highlights.",
    price: 22300,
    color: "#2563eb",
    borderPalette: ["#2563eb", "#111827", "#93c5fd"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-lunar-blue",
    name: "Lunar Blue Border",
    description: "A pale blue border with white body and warm gold edge flashes.",
    price: 22200,
    color: "#7dd3fc",
    borderPalette: ["#7dd3fc", "#ffffff", "#fde68a"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-royal-ember",
    name: "Royal Ember Border",
    description: "A navy-red-white diagonal frame with a cleaner late-evening glow.",
    price: 23100,
    color: "#1e3a8a",
    borderPalette: ["#1e3a8a", "#ef4444", "#ffffff"],
    borderStyle: "tricolor-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-ivory-crown",
    name: "Ivory Crown Border",
    description: "A white-gold frame touched with a faint royal violet finish.",
    price: 22900,
    color: "#ffffff",
    borderPalette: ["#ffffff", "#facc15", "#c084fc"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-cobalt-gala",
    name: "Cobalt Gala Border",
    description: "A louder blue-red-gold tricolor frame for dramatic profile presence.",
    price: 23200,
    color: "#1d4ed8",
    borderPalette: ["#1d4ed8", "#dc2626", "#f59e0b"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-scarlet-march",
    name: "Scarlet March Border",
    description: "A striped red-white frame with darker navy pacing between the bands.",
    price: 22700,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#ffffff", "#1e3a8a"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-solar-garnet",
    name: "Solar Garnet Border",
    description: "A gold-red-black diagonal frame that reads warm and expensive.",
    price: 22900,
    color: "#f59e0b",
    borderPalette: ["#f59e0b", "#b91c1c", "#111827"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-canary-depth",
    name: "Canary Depth Border",
    description: "A yellow-navy-white banded frame with stronger stadium contrast.",
    price: 23100,
    color: "#facc15",
    borderPalette: ["#facc15", "#1e3a8a", "#ffffff"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-monochrome-roar",
    name: "Monochrome Roar Border",
    description: "A black-white split frame with a colder silver edge polish.",
    price: 22300,
    color: "#111827",
    borderPalette: ["#111827", "#ffffff", "#d1d5db"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-bordeaux-tide",
    name: "Bordeaux Tide Border",
    description: "A claret-cyan frame with pale trim to keep the contrast sharp.",
    price: 22600,
    color: "#7f1d1d",
    borderPalette: ["#7f1d1d", "#67e8f9", "#fff1f2"],
    borderStyle: "tricolor-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-sunset-loom",
    name: "Sunset Loom Border",
    description: "A yellow-red frame with dark edge lines for a hotter rotating look.",
    price: 22500,
    color: "#facc15",
    borderPalette: ["#facc15", "#dc2626", "#111827"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-forest-mist",
    name: "Forest Mist Border",
    description: "A green-black diagonal border cooled down with white stadium light.",
    price: 22400,
    color: "#15803d",
    borderPalette: ["#15803d", "#111827", "#f8fafc"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-albion-banner",
    name: "Albion Banner Border",
    description: "A white-red-blue frame with a sharper center ribbon and cleaner edges.",
    price: 21400,
    color: "#ffffff",
    borderPalette: ["#ffffff", "#dc2626", "#1e3a8a"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-iron-banner",
    name: "Iron Banner Border",
    description: "A black-red-gold tricolor frame with heavier prestige contrast.",
    price: 21800,
    color: "#111827",
    borderPalette: ["#111827", "#dc2626", "#facc15"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-azure-banner",
    name: "Azure Banner Border",
    description: "A bright azure-white border with colder sky-light depth.",
    price: 21600,
    color: "#2563eb",
    borderPalette: ["#2563eb", "#ffffff", "#dbeafe"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-cobalt-tricolor",
    name: "Cobalt Tricolor Border",
    description: "A blue-white-red split frame that stays crisp even at smaller sizes.",
    price: 21800,
    color: "#1d4ed8",
    borderPalette: ["#1d4ed8", "#ffffff", "#dc2626"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-ember-gold-banner",
    name: "Ember Gold Banner Border",
    description: "A black-gold-red slice border with hotter circular movement.",
    price: 22000,
    color: "#111827",
    borderPalette: ["#111827", "#facc15", "#ef4444"],
    borderStyle: "conic-slice",
  }),
  footballBorder({
    id: "profile-border-rotating-amber-drift",
    name: "Amber Drift Border",
    description: "A warm orange frame cooled by deeper blue and pale match-light trim.",
    price: 21700,
    color: "#f97316",
    borderPalette: ["#f97316", "#1e3a8a", "#fff7ed"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-iberian-pulse",
    name: "Iberian Pulse Border",
    description: "A red-yellow-navy tricolor frame with a bright public-card read.",
    price: 21900,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#facc15", "#1e3a8a"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-ruby-frost",
    name: "Ruby Frost Border",
    description: "A red-white diagonal border sharpened with a dark frostline edge.",
    price: 21500,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#ffffff", "#111827"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-alpine-tempo",
    name: "Alpine Tempo Border",
    description: "A red-white split frame moderated by cooler graphite pacing.",
    price: 21400,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#ffffff", "#475569"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-nordic-tide",
    name: "Nordic Tide Border",
    description: "A darker red frame with white bodywork and lighter crimson edge flow.",
    price: 21400,
    color: "#b91c1c",
    borderPalette: ["#b91c1c", "#ffffff", "#fca5a5"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-aurora-steel",
    name: "Aurora Steel Border",
    description: "A blue-gold diagonal frame balanced by colder silver stadium light.",
    price: 21700,
    color: "#1d4ed8",
    borderPalette: ["#1d4ed8", "#facc15", "#dbeafe"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-glacier-ribbon",
    name: "Glacier Ribbon Border",
    description: "A red-white slate slice border with a colder rotating finish.",
    price: 21600,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#ffffff", "#334155"],
    borderStyle: "conic-slice",
  }),
  footballBorder({
    id: "profile-border-rotating-amber-crest",
    name: "Amber Crest Border",
    description: "A pale split frame with red body and muted steel underlighting.",
    price: 21400,
    color: "#ffffff",
    borderPalette: ["#ffffff", "#dc2626", "#94a3b8"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-fjord-current",
    name: "Fjord Current Border",
    description: "A red-navy-white ribbon frame with stronger late-game contrast.",
    price: 21900,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#1e3a8a", "#ffffff"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-winter-aurora",
    name: "Winter Aurora Border",
    description: "An icy white-blue glow border that feels colder than the usual sky palette.",
    price: 21300,
    color: "#f8fafc",
    borderPalette: ["#f8fafc", "#38bdf8", "#dbeafe"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-liberty-pulse",
    name: "Liberty Pulse Border",
    description: "A red-white-blue pinstripe frame tuned for louder public recognition.",
    price: 22000,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#ffffff", "#1d4ed8"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-northern-ice",
    name: "Northern Ice Border",
    description: "A clean red-white diagonal frame finished with colder pale accents.",
    price: 21400,
    color: "#dc2626",
    borderPalette: ["#dc2626", "#ffffff", "#fee2e2"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-celeste-gold",
    name: "Celeste Gold Border",
    description: "A pale sky tricolor border with white center space and warm gold trim.",
    price: 21900,
    color: "#7dd3fc",
    borderPalette: ["#7dd3fc", "#ffffff", "#fde68a"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-verde-wave",
    name: "Verde Wave Border",
    description: "A green-gold-blue slice border with a brighter celebratory read.",
    price: 22100,
    color: "#16a34a",
    borderPalette: ["#16a34a", "#facc15", "#2563eb"],
    borderStyle: "conic-slice",
  }),
  footballBorder({
    id: "profile-border-rotating-sakura-current",
    name: "Sakura Current Border",
    description: "A white-red glow frame cooled down by faint blue night-match edges.",
    price: 21600,
    color: "#ffffff",
    borderPalette: ["#ffffff", "#dc2626", "#1e40af"],
    borderStyle: "stadium-glow",
  }),
];
