export const PROFILE_FRAME_COSMETIC_TYPES = [
  "profile-frame-bottom",
  "profile-frame-side",
  "profile-frame-corner",
  "profile-frame-top",
  "profile-frame-overlay",
  "profile-frame-particles",
] as const;

export type ProfileFrameCosmeticType = (typeof PROFILE_FRAME_COSMETIC_TYPES)[number];

export type ProfileFrameDecorationMotif =
  | "ribbon-bow"
  | "hanging-heart-lock"
  | "hanging-moon-bell"
  | "wax-seal"
  | "wax-crest"
  | "gem-clasp"
  | "rose-cluster"
  | "corner-bows"
  | "top-crown"
  | "top-crest"
  | "overlay-lace"
  | "overlay-drape"
  | "side-tassels"
  | "side-cat-pair"
  | "side-dog-pair"
  | "side-bunny-pair"
  | "side-fox-pair"
  | "side-bear-pair"
  | "particles-hearts"
  | "particles-petals"
  | "particles-dust"
  | "particles-embers";

export type ProfileFrameDecorationDefinition = {
  id: string;
  name: string;
  description: string;
  type: ProfileFrameCosmeticType;
  price: number;
  motif: ProfileFrameDecorationMotif;
  palette: [string, string, string?];
  metal?: string;
  shadow?: string;
};

export type ProfileFrameCatalogItem = Pick<
  ProfileFrameDecorationDefinition,
  "description" | "id" | "name" | "price" | "type"
>;

const definition = (
  item: ProfileFrameDecorationDefinition,
): ProfileFrameDecorationDefinition => item;

export const profileFrameDecorationDefinitions: ProfileFrameDecorationDefinition[] = [
  definition({
    id: "frame-bottom-satin-noir",
    name: "Satin Noir Bow",
    description: "A large noir ribbon with bright candy trim for the lower frame.",
    type: "profile-frame-bottom",
    price: 22000,
    motif: "ribbon-bow",
    palette: ["#26112f", "#f472b6", "#fbcfe8"],
    metal: "#facc15",
    shadow: "#ec4899",
  }),
  definition({
    id: "frame-bottom-sugar-heart",
    name: "Sugar Heart Bow",
    description: "Soft layered ribbon loops with a sweeter pastel heart finish.",
    type: "profile-frame-bottom",
    price: 21000,
    motif: "ribbon-bow",
    palette: ["#fb7185", "#f9a8d4", "#fff1f2"],
    metal: "#fde68a",
    shadow: "#fb7185",
  }),
  definition({
    id: "frame-bottom-heart-lock",
    name: "Heart Lock Drop",
    description: "A center bow with a dangling lock charm that feels expensive and clingy.",
    type: "profile-frame-bottom",
    price: 24500,
    motif: "hanging-heart-lock",
    palette: ["#6b2149", "#f472b6", "#ffe4e6"],
    metal: "#facc15",
    shadow: "#be185d",
  }),
  definition({
    id: "frame-bottom-moon-bell",
    name: "Moon Bell Drop",
    description: "A moonlit clasp with a tiny bell swinging below the frame.",
    type: "profile-frame-bottom",
    price: 24800,
    motif: "hanging-moon-bell",
    palette: ["#312e81", "#a78bfa", "#e0e7ff"],
    metal: "#cbd5e1",
    shadow: "#7c3aed",
  }),
  definition({
    id: "frame-bottom-royal-seal",
    name: "Royal Wax Seal",
    description: "Heavy ribbon tails held together with a formal crimson seal.",
    type: "profile-frame-bottom",
    price: 25800,
    motif: "wax-seal",
    palette: ["#7f1d1d", "#ef4444", "#fee2e2"],
    metal: "#fcd34d",
    shadow: "#991b1b",
  }),
  definition({
    id: "frame-bottom-obsidian-crest",
    name: "Obsidian Crest Seal",
    description: "A darker crest and lacquered tails for colder prestige.",
    type: "profile-frame-bottom",
    price: 26800,
    motif: "wax-crest",
    palette: ["#111827", "#374151", "#f9a8d4"],
    metal: "#facc15",
    shadow: "#111827",
  }),
  definition({
    id: "frame-bottom-aurora-clasp",
    name: "Aurora Gem Clasp",
    description: "A jeweled clasp with split silk tails and a glassy center stone.",
    type: "profile-frame-bottom",
    price: 25200,
    motif: "gem-clasp",
    palette: ["#14b8a6", "#67e8f9", "#ecfeff"],
    metal: "#f8fafc",
    shadow: "#0f766e",
  }),
  definition({
    id: "frame-bottom-rose-bouquet",
    name: "Rose Bouquet Cluster",
    description: "Three small roses and leaves arranged under the showcase frame.",
    type: "profile-frame-bottom",
    price: 23800,
    motif: "rose-cluster",
    palette: ["#f43f5e", "#fda4af", "#fef2f2"],
    metal: "#4ade80",
    shadow: "#be123c",
  }),
  definition({
    id: "frame-corner-sugarpink",
    name: "Sugarpink Corner Bows",
    description: "Small corner bows that soften the lower frame immediately.",
    type: "profile-frame-corner",
    price: 16800,
    motif: "corner-bows",
    palette: ["#fb7185", "#f9a8d4", "#fff1f2"],
    metal: "#fde68a",
    shadow: "#fb7185",
  }),
  definition({
    id: "frame-corner-noir-gold",
    name: "Noir Gold Corner Bows",
    description: "A sharper corner pair with black satin and gold trim.",
    type: "profile-frame-corner",
    price: 17600,
    motif: "corner-bows",
    palette: ["#1f2937", "#111827", "#facc15"],
    metal: "#facc15",
    shadow: "#111827",
  }),
  definition({
    id: "frame-corner-mint-lace",
    name: "Mint Lace Corner Bows",
    description: "Brighter lace-toned corners that read playful instead of heavy.",
    type: "profile-frame-corner",
    price: 17000,
    motif: "corner-bows",
    palette: ["#5eead4", "#99f6e4", "#ecfeff"],
    metal: "#f8fafc",
    shadow: "#14b8a6",
  }),
  definition({
    id: "frame-corner-wine-velvet",
    name: "Wine Velvet Corner Bows",
    description: "A warmer velvet pair for darker border palettes.",
    type: "profile-frame-corner",
    price: 17200,
    motif: "corner-bows",
    palette: ["#7f1d1d", "#be123c", "#ffe4e6"],
    metal: "#fda4af",
    shadow: "#881337",
  }),
  definition({
    id: "frame-top-gilded-crown",
    name: "Gilded Crown Pin",
    description: "A clean crown pin placed exactly over the frame center.",
    type: "profile-frame-top",
    price: 18800,
    motif: "top-crown",
    palette: ["#d97706", "#facc15", "#fef3c7"],
    metal: "#fde68a",
    shadow: "#b45309",
  }),
  definition({
    id: "frame-top-roseglass-crown",
    name: "Roseglass Crown Pin",
    description: "A softer tiara-style crown with glass-pink stones.",
    type: "profile-frame-top",
    price: 19400,
    motif: "top-crown",
    palette: ["#f472b6", "#fbcfe8", "#fff1f2"],
    metal: "#fdf2f8",
    shadow: "#ec4899",
  }),
  definition({
    id: "frame-top-night-crest",
    name: "Night Crest Pin",
    description: "A small crest medallion for a colder ceremonial look.",
    type: "profile-frame-top",
    price: 19600,
    motif: "top-crest",
    palette: ["#0f172a", "#475569", "#cbd5e1"],
    metal: "#cbd5e1",
    shadow: "#0f172a",
  }),
  definition({
    id: "frame-top-pearl-heart-pin",
    name: "Pearl Heart Pin",
    description: "A heart crest pin that reads sweeter than a strict crown.",
    type: "profile-frame-top",
    price: 19000,
    motif: "top-crest",
    palette: ["#f9a8d4", "#fde2e8", "#fff1f2"],
    metal: "#f8fafc",
    shadow: "#f472b6",
  }),
  definition({
    id: "frame-side-noir-tassels",
    name: "Noir Tassel Pair",
    description: "Long side tassels with darker cords and brighter tips.",
    type: "profile-frame-side",
    price: 20500,
    motif: "side-tassels",
    palette: ["#111827", "#374151", "#f9a8d4"],
    metal: "#facc15",
    shadow: "#111827",
  }),
  definition({
    id: "frame-side-rosegold-tassels",
    name: "Rosegold Tassel Pair",
    description: "Beaded tassels with lighter satin cords and a warm metallic tip.",
    type: "profile-frame-side",
    price: 21000,
    motif: "side-tassels",
    palette: ["#f472b6", "#fdba74", "#fff7ed"],
    metal: "#fdba74",
    shadow: "#ea580c",
  }),
  definition({
    id: "frame-side-sleepy-cats",
    name: "Sleepy Cat Pair",
    description: "Two peeking cats holding the lower frame corners like plush guards.",
    type: "profile-frame-side",
    price: 23400,
    motif: "side-cat-pair",
    palette: ["#f472b6", "#fbcfe8", "#fff1f2"],
    metal: "#fcd34d",
    shadow: "#db2777",
  }),
  definition({
    id: "frame-side-guardian-pups",
    name: "Guardian Pup Pair",
    description: "A softer puppy pair for a friendlier lower-frame silhouette.",
    type: "profile-frame-side",
    price: 23200,
    motif: "side-dog-pair",
    palette: ["#f59e0b", "#fde68a", "#fff7ed"],
    metal: "#fef3c7",
    shadow: "#d97706",
  }),
  definition({
    id: "frame-side-cupid-bunnies",
    name: "Cupid Bunny Pair",
    description: "Two upright bunnies peeking in with tall ears and tiny hearts.",
    type: "profile-frame-side",
    price: 23600,
    motif: "side-bunny-pair",
    palette: ["#f9a8d4", "#fde2e8", "#fff1f2"],
    metal: "#fda4af",
    shadow: "#ec4899",
  }),
  definition({
    id: "frame-side-velvet-foxes",
    name: "Velvet Fox Pair",
    description: "Sharper fox faces that make the frame feel a bit more cunning.",
    type: "profile-frame-side",
    price: 23900,
    motif: "side-fox-pair",
    palette: ["#fb7185", "#fdba74", "#fff7ed"],
    metal: "#fef3c7",
    shadow: "#c2410c",
  }),
  definition({
    id: "frame-side-plush-bears",
    name: "Plush Bear Pair",
    description: "Rounder bear faces for a toy-shelf kind of sweetness.",
    type: "profile-frame-side",
    price: 23000,
    motif: "side-bear-pair",
    palette: ["#a16207", "#d6b38d", "#fef3c7"],
    metal: "#fde68a",
    shadow: "#854d0e",
  }),
  definition({
    id: "frame-overlay-pearl-lace",
    name: "Pearl Lace Frill",
    description: "A soft lace hem stitched across the lower part of the frame.",
    type: "profile-frame-overlay",
    price: 21200,
    motif: "overlay-lace",
    palette: ["#f8fafc", "#fde2e8", "#fff1f2"],
    metal: "#e2e8f0",
    shadow: "#fbcfe8",
  }),
  definition({
    id: "frame-overlay-noir-lace",
    name: "Noir Lace Frill",
    description: "Black lace trim that makes brighter avatars pop more.",
    type: "profile-frame-overlay",
    price: 21400,
    motif: "overlay-lace",
    palette: ["#111827", "#374151", "#f9a8d4"],
    metal: "#cbd5e1",
    shadow: "#111827",
  }),
  definition({
    id: "frame-overlay-royal-drape",
    name: "Royal Mini Drape",
    description: "Two velvet drapes hanging inward to stage the lower frame.",
    type: "profile-frame-overlay",
    price: 22800,
    motif: "overlay-drape",
    palette: ["#7c3aed", "#312e81", "#fbcfe8"],
    metal: "#facc15",
    shadow: "#4c1d95",
  }),
  definition({
    id: "frame-overlay-candy-drape",
    name: "Candy Mini Drape",
    description: "A lighter drape pair that feels playful instead of regal.",
    type: "profile-frame-overlay",
    price: 22400,
    motif: "overlay-drape",
    palette: ["#fb7185", "#f472b6", "#fff1f2"],
    metal: "#fde68a",
    shadow: "#e11d48",
  }),
  definition({
    id: "frame-particles-soft-hearts",
    name: "Soft Heart Particles",
    description: "Small floating hearts that sit comfortably around the frame edges.",
    type: "profile-frame-particles",
    price: 18600,
    motif: "particles-hearts",
    palette: ["#f472b6", "#f9a8d4", "#fff1f2"],
    metal: "#fde68a",
    shadow: "#ec4899",
  }),
  definition({
    id: "frame-particles-rose-petals",
    name: "Rose Petal Drift",
    description: "Tiny rose petals drifting lightly inside the showcase area.",
    type: "profile-frame-particles",
    price: 18800,
    motif: "particles-petals",
    palette: ["#fb7185", "#f43f5e", "#ffe4e6"],
    metal: "#fda4af",
    shadow: "#be123c",
  }),
  definition({
    id: "frame-particles-gilded-dust",
    name: "Gilded Dust",
    description: "Warm gold dust and sparkles for a richer premium finish.",
    type: "profile-frame-particles",
    price: 19200,
    motif: "particles-dust",
    palette: ["#f59e0b", "#facc15", "#fef3c7"],
    metal: "#fef3c7",
    shadow: "#d97706",
  }),
  definition({
    id: "frame-particles-embers",
    name: "Velvet Embers",
    description: "Hot drifting embers for darker or more dramatic frame looks.",
    type: "profile-frame-particles",
    price: 19400,
    motif: "particles-embers",
    palette: ["#ef4444", "#fb7185", "#fff7ed"],
    metal: "#fdba74",
    shadow: "#b91c1c",
  }),
  definition({
    id: "frame-bottom-frosted-opera",
    name: "Frosted Opera Bow",
    description: "An icy satin bow with silver edges and a blue-to-lilac blend.",
    type: "profile-frame-bottom",
    price: 22300,
    motif: "ribbon-bow",
    palette: ["#dbeafe", "#a5b4fc", "#ffffff"],
    metal: "#e2e8f0",
    shadow: "#818cf8",
  }),
  definition({
    id: "frame-bottom-prism-cabaret",
    name: "Prism Cabaret Bow",
    description: "A louder three-tone bow shifting from coral to violet to gold.",
    type: "profile-frame-bottom",
    price: 22900,
    motif: "ribbon-bow",
    palette: ["#fb7185", "#8b5cf6", "#fde68a"],
    metal: "#fde68a",
    shadow: "#c026d3",
  }),
  definition({
    id: "frame-bottom-cherry-locket",
    name: "Cherry Locket Drop",
    description: "A richer heart-lock version with wine red silk and bright pearl trim.",
    type: "profile-frame-bottom",
    price: 24700,
    motif: "hanging-heart-lock",
    palette: ["#9f1239", "#fb7185", "#fff1f2"],
    metal: "#f8fafc",
    shadow: "#be123c",
  }),
  definition({
    id: "frame-bottom-starlit-bell",
    name: "Starlit Bell Drop",
    description: "A colder moon-bell mix with midnight blue, lilac, and pale starlight.",
    type: "profile-frame-bottom",
    price: 24900,
    motif: "hanging-moon-bell",
    palette: ["#1e1b4b", "#818cf8", "#e0f2fe"],
    metal: "#cbd5e1",
    shadow: "#4338ca",
  }),
  definition({
    id: "frame-bottom-ivory-seal",
    name: "Ivory Wax Seal",
    description: "Cream silk tails and a champagne wax seal for a softer ceremonial look.",
    type: "profile-frame-bottom",
    price: 25900,
    motif: "wax-seal",
    palette: ["#fef3c7", "#fcd34d", "#fff7ed"],
    metal: "#f8fafc",
    shadow: "#d97706",
  }),
  definition({
    id: "frame-bottom-midnight-crest",
    name: "Midnight Crest Seal",
    description: "A navy-black crest seal with colder silver accents and deeper contrast.",
    type: "profile-frame-bottom",
    price: 26900,
    motif: "wax-crest",
    palette: ["#0f172a", "#1e3a8a", "#dbeafe"],
    metal: "#e2e8f0",
    shadow: "#0f172a",
  }),
  definition({
    id: "frame-bottom-prism-clasp",
    name: "Prism Gem Clasp",
    description: "A glass-clasp variant with teal, orchid, and pearl all layered together.",
    type: "profile-frame-bottom",
    price: 25400,
    motif: "gem-clasp",
    palette: ["#2dd4bf", "#c084fc", "#f8fafc"],
    metal: "#f8fafc",
    shadow: "#7c3aed",
  }),
  definition({
    id: "frame-bottom-lavender-bouquet",
    name: "Lavender Bloom Cluster",
    description: "Petal clusters in lilac, blush, and cream for a softer bottom flourish.",
    type: "profile-frame-bottom",
    price: 24100,
    motif: "rose-cluster",
    palette: ["#a78bfa", "#f9a8d4", "#fff7ed"],
    metal: "#86efac",
    shadow: "#8b5cf6",
  }),
  definition({
    id: "frame-corner-pearl-sky",
    name: "Pearl Sky Corner Bows",
    description: "A pale blue and pearl corner pair that reads airy instead of sugary.",
    type: "profile-frame-corner",
    price: 17100,
    motif: "corner-bows",
    palette: ["#93c5fd", "#dbeafe", "#ffffff"],
    metal: "#f8fafc",
    shadow: "#60a5fa",
  }),
  definition({
    id: "frame-corner-sunset-ribbon",
    name: "Sunset Ribbon Corner Bows",
    description: "Coral, amber, and pink layered together for a louder lower-corner pop.",
    type: "profile-frame-corner",
    price: 17500,
    motif: "corner-bows",
    palette: ["#fb7185", "#fdba74", "#fef3c7"],
    metal: "#fde68a",
    shadow: "#ea580c",
  }),
  definition({
    id: "frame-corner-lilac-frost",
    name: "Lilac Frost Corner Bows",
    description: "A cooler lilac version with pearl tips and frosted shine.",
    type: "profile-frame-corner",
    price: 17300,
    motif: "corner-bows",
    palette: ["#8b5cf6", "#c4b5fd", "#eef2ff"],
    metal: "#e2e8f0",
    shadow: "#7c3aed",
  }),
  definition({
    id: "frame-corner-emerald-noir",
    name: "Emerald Noir Corner Bows",
    description: "Dark corners pierced with emerald trim for sharper contrast.",
    type: "profile-frame-corner",
    price: 17800,
    motif: "corner-bows",
    palette: ["#111827", "#10b981", "#d1fae5"],
    metal: "#a7f3d0",
    shadow: "#065f46",
  }),
  definition({
    id: "frame-top-sapphire-crown",
    name: "Sapphire Crown Pin",
    description: "A crown pin with colder blue stones and a cleaner royal silhouette.",
    type: "profile-frame-top",
    price: 19100,
    motif: "top-crown",
    palette: ["#1d4ed8", "#60a5fa", "#dbeafe"],
    metal: "#e0f2fe",
    shadow: "#1e3a8a",
  }),
  definition({
    id: "frame-top-sunset-tiara",
    name: "Sunset Tiara Pin",
    description: "A brighter crown variant mixing peach, rose, and gold like a sunset tiara.",
    type: "profile-frame-top",
    price: 19500,
    motif: "top-crown",
    palette: ["#fb7185", "#fdba74", "#fef3c7"],
    metal: "#fde68a",
    shadow: "#ea580c",
  }),
  definition({
    id: "frame-top-ruby-crest",
    name: "Ruby Crest Pin",
    description: "A formal crest pin with darker red lacquer and a sharper ceremonial face.",
    type: "profile-frame-top",
    price: 19700,
    motif: "top-crest",
    palette: ["#991b1b", "#ef4444", "#fee2e2"],
    metal: "#fca5a5",
    shadow: "#7f1d1d",
  }),
  definition({
    id: "frame-top-mint-heart-pin",
    name: "Mint Heart Pin",
    description: "A sweeter heart pin with mint glass, pearl trim, and lighter energy.",
    type: "profile-frame-top",
    price: 19200,
    motif: "top-crest",
    palette: ["#2dd4bf", "#99f6e4", "#ecfeff"],
    metal: "#f8fafc",
    shadow: "#0f766e",
  }),
  definition({
    id: "frame-side-ivory-tassels",
    name: "Ivory Tassel Pair",
    description: "Long cream tassels with pearl cords for a cleaner romantic look.",
    type: "profile-frame-side",
    price: 20800,
    motif: "side-tassels",
    palette: ["#fff7ed", "#fde68a", "#ffffff"],
    metal: "#f8fafc",
    shadow: "#d6d3d1",
  }),
  definition({
    id: "frame-side-twilight-tassels",
    name: "Twilight Tassel Pair",
    description: "A purple-blue tassel mix that feels colder and more luxurious.",
    type: "profile-frame-side",
    price: 21400,
    motif: "side-tassels",
    palette: ["#312e81", "#8b5cf6", "#e0e7ff"],
    metal: "#cbd5e1",
    shadow: "#4338ca",
  }),
  definition({
    id: "frame-side-moon-cats",
    name: "Moon Cat Pair",
    description: "Peeking cats recolored in moonstone blues and silver instead of pink.",
    type: "profile-frame-side",
    price: 23600,
    motif: "side-cat-pair",
    palette: ["#93c5fd", "#e0f2fe", "#ffffff"],
    metal: "#e2e8f0",
    shadow: "#60a5fa",
  }),
  definition({
    id: "frame-side-cinnamon-pups",
    name: "Cinnamon Pup Pair",
    description: "Warmer puppy guards with caramel fur and soft cream details.",
    type: "profile-frame-side",
    price: 23400,
    motif: "side-dog-pair",
    palette: ["#c2410c", "#fdba74", "#fff7ed"],
    metal: "#fde68a",
    shadow: "#9a3412",
  }),
  definition({
    id: "frame-side-snow-bunnies",
    name: "Snow Bunny Pair",
    description: "A frosted bunny version with icy whites and pale lavender accents.",
    type: "profile-frame-side",
    price: 23800,
    motif: "side-bunny-pair",
    palette: ["#e5e7eb", "#c4b5fd", "#ffffff"],
    metal: "#f8fafc",
    shadow: "#a78bfa",
  }),
  definition({
    id: "frame-side-ember-foxes",
    name: "Ember Fox Pair",
    description: "Fox guards recolored with ember orange, gold, and a hotter dramatic finish.",
    type: "profile-frame-side",
    price: 24100,
    motif: "side-fox-pair",
    palette: ["#ea580c", "#fb923c", "#ffedd5"],
    metal: "#fde68a",
    shadow: "#c2410c",
  }),
  definition({
    id: "frame-side-honey-bears",
    name: "Honey Bear Pair",
    description: "Bear guards in honey, caramel, and cream for a richer toy-box palette.",
    type: "profile-frame-side",
    price: 23300,
    motif: "side-bear-pair",
    palette: ["#a16207", "#f59e0b", "#fef3c7"],
    metal: "#fde68a",
    shadow: "#854d0e",
  }),
  definition({
    id: "frame-overlay-silver-lace",
    name: "Silver Lace Frill",
    description: "An icier lace hem with pearl-silver stitching across the lower frame.",
    type: "profile-frame-overlay",
    price: 21500,
    motif: "overlay-lace",
    palette: ["#e2e8f0", "#bae6fd", "#ffffff"],
    metal: "#f8fafc",
    shadow: "#94a3b8",
  }),
  definition({
    id: "frame-overlay-rose-noir-lace",
    name: "Rose Noir Lace Frill",
    description: "Black lace with rose-pink thread running through the trim.",
    type: "profile-frame-overlay",
    price: 21700,
    motif: "overlay-lace",
    palette: ["#111827", "#f472b6", "#fff1f2"],
    metal: "#f9a8d4",
    shadow: "#be185d",
  }),
  definition({
    id: "frame-overlay-sapphire-drape",
    name: "Sapphire Mini Drape",
    description: "Side drapes recolored in sapphire, cobalt, and pale pearl.",
    type: "profile-frame-overlay",
    price: 23100,
    motif: "overlay-drape",
    palette: ["#2563eb", "#1d4ed8", "#dbeafe"],
    metal: "#e0f2fe",
    shadow: "#1e3a8a",
  }),
  definition({
    id: "frame-overlay-aurora-drape",
    name: "Aurora Mini Drape",
    description: "A brighter drape set mixing mint, lilac, and pearl all at once.",
    type: "profile-frame-overlay",
    price: 22900,
    motif: "overlay-drape",
    palette: ["#2dd4bf", "#a78bfa", "#f8fafc"],
    metal: "#f8fafc",
    shadow: "#7c3aed",
  }),
  definition({
    id: "frame-particles-candy-hearts",
    name: "Candy Heart Sprinkle",
    description: "Brighter candy hearts in pink, coral, and cream drifting around the frame.",
    type: "profile-frame-particles",
    price: 18900,
    motif: "particles-hearts",
    palette: ["#fb7185", "#f472b6", "#fff7ed"],
    metal: "#fde68a",
    shadow: "#e11d48",
  }),
  definition({
    id: "frame-particles-sakura-petals",
    name: "Sakura Petal Drift",
    description: "A softer petal variant leaning blossom-pink instead of deep rose.",
    type: "profile-frame-particles",
    price: 19100,
    motif: "particles-petals",
    palette: ["#f9a8d4", "#fbcfe8", "#fff1f2"],
    metal: "#f8fafc",
    shadow: "#ec4899",
  }),
  definition({
    id: "frame-particles-prism-dust",
    name: "Prism Dust",
    description: "Sparkle dust with blue, lilac, and pale gold mixed together.",
    type: "profile-frame-particles",
    price: 19500,
    motif: "particles-dust",
    palette: ["#60a5fa", "#a78bfa", "#fde68a"],
    metal: "#f8fafc",
    shadow: "#7c3aed",
  }),
  definition({
    id: "frame-particles-amethyst-embers",
    name: "Amethyst Embers",
    description: "Dark floating embers recolored into magenta-violet heat.",
    type: "profile-frame-particles",
    price: 19700,
    motif: "particles-embers",
    palette: ["#c026d3", "#8b5cf6", "#fdf4ff"],
    metal: "#f9a8d4",
    shadow: "#86198f",
  }),
];

export const rotatingProfileFrameCosmeticItems: ProfileFrameCatalogItem[] =
  profileFrameDecorationDefinitions.map(
    ({ description, id, name, price, type }) => ({
      description,
      id,
      name,
      price,
      type,
    }),
  );

const definitionMap = new Map(
  profileFrameDecorationDefinitions.map((item) => [item.id, item]),
);

export function getProfileFrameDecorationDefinition(id: string) {
  return definitionMap.get(id) ?? null;
}

export function isProfileFrameCosmeticType(
  value: string | null | undefined,
): value is ProfileFrameCosmeticType {
  return PROFILE_FRAME_COSMETIC_TYPES.includes(
    value as ProfileFrameCosmeticType,
  );
}

export function getProfileFrameCosmeticTypeLabel(type: ProfileFrameCosmeticType) {
  switch (type) {
    case "profile-frame-bottom":
      return "Bottom Ornament";
    case "profile-frame-side":
      return "Side Ornament";
    case "profile-frame-corner":
      return "Corner Ornament";
    case "profile-frame-top":
      return "Top Pin";
    case "profile-frame-overlay":
      return "Frame Overlay";
    case "profile-frame-particles":
      return "Particles";
    default:
      return "Frame Cosmetic";
  }
}
