export type ProfileBorderStyle =
  | "solid"
  | "split-diagonal"
  | "split-vertical"
  | "tricolor-band"
  | "tricolor-diagonal"
  | "pinstripe"
  | "edge-stripe"
  | "stadium-glow"
  | "conic-slice";

export type ProfileBorderCatalogItem = {
  id: string;
  name: string;
  description: string;
  type: "profile-border";
  price: number;
  color: string;
  borderPalette: [string, string, string?];
  borderStyle: ProfileBorderStyle;
  isArchived?: boolean;
};

function footballBorder(
  item: Omit<ProfileBorderCatalogItem, "type">,
): ProfileBorderCatalogItem {
  return {
    ...item,
    type: "profile-border",
  };
}

export const footballInspiredRotatingBorders: ProfileBorderCatalogItem[] = [
  // === ENGLAND CLUBS ===
  footballBorder({
    id: "profile-border-rotating-manchester-city",
    name: "Manchester City Border",
    description: "Ethereal sky blue and white split. Floodlights and Etihad precision.",
    price: 10000,
    color: "#6CABDD",
    borderPalette: ["#6CABDD", "#FFFFFF"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-arsenal",
    name: "Arsenal Border",
    description: "Bold cannon red cut against pure white. North London fire.",
    price: 10000,
    color: "#EF0107",
    borderPalette: ["#EF0107", "#FFFFFF", "#DBA111"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-liverpool",
    name: "Liverpool Border",
    description: "Anfield red with a sharp white blade. This means more.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#FFFFFF"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-chelsea",
    name: "Chelsea Border",
    description: "Deep royal blue and white. Stamford Bridge steel.",
    price: 10000,
    color: "#034694",
    borderPalette: ["#034694", "#FFFFFF"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-manchester-united",
    name: "Manchester United Border",
    description: "Theatre of Dreams red slashed with black. Theatre of Red.",
    price: 10000,
    color: "#DA020E",
    borderPalette: ["#DA020E", "#000000"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-tottenham",
    name: "Tottenham Border",
    description: "Navy and lilywhite. Clean, arrogant, North London class.",
    price: 10000,
    color: "#132257",
    borderPalette: ["#132257", "#FFFFFF"],
    borderStyle: "stadium-glow",
  }),

  // === GERMANY CLUBS ===
  footballBorder({
    id: "profile-border-rotating-dortmund",
    name: "Borussia Dortmund Border",
    description: "Screaming yellow and black. Signal Iduna Park wall of sound.",
    price: 10000,
    color: "#FDE100",
    borderPalette: ["#FDE100", "#000000"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-bayern-munich",
    name: "Bayern Munich Border",
    description: "Bavarian red and white. The machine never stops.",
    price: 10000,
    color: "#DC052D",
    borderPalette: ["#DC052D", "#FFFFFF"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-hertha-berlin",
    name: "Hertha Berlin Border",
    description: "Old Berlin blue and white. Capital city pride.",
    price: 10000,
    color: "#005CA9",
    borderPalette: ["#005CA9", "#FFFFFF"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-rb-leipzig",
    name: "RB Leipzig Border",
    description: "Modern red energy. Fast, vertical, relentless.",
    price: 10000,
    color: "#E30613",
    borderPalette: ["#E30613", "#FFFFFF"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-union-berlin",
    name: "Union Berlin Border",
    description: "Working class red. Stadium of the people.",
    price: 10000,
    color: "#E30613",
    borderPalette: ["#E30613", "#FFFFFF"],
    borderStyle: "edge-stripe",
  }),

  // === ITALY CLUBS ===
  footballBorder({
    id: "profile-border-rotating-inter-milan",
    name: "Inter Milan Border",
    description: "Nerazzurri. Black and blue royalty from San Siro.",
    price: 10000,
    color: "#0068A8",
    borderPalette: ["#0068A8", "#000000"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-ac-milan",
    name: "AC Milan Border",
    description: "Rossoneri. Blood red and black. Pure Italian elegance.",
    price: 10000,
    color: "#FB090B",
    borderPalette: ["#FB090B", "#000000"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-napoli",
    name: "Napoli Border",
    description: "Azzurri sky blue from the bay. Maradona's city.",
    price: 10000,
    color: "#12A0D7",
    borderPalette: ["#12A0D7", "#FFFFFF"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-juventus",
    name: "Juventus Border",
    description: "Black and white stripes. The Old Lady with gold trim.",
    price: 10000,
    color: "#000000",
    borderPalette: ["#000000", "#FFFFFF", "#D4AF37"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-roma",
    name: "AS Roma Border",
    description: "Roman red and imperial gold. Wolves of the capital.",
    price: 10000,
    color: "#8E1F2F",
    borderPalette: ["#8E1F2F", "#D4AF37"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-atalanta",
    name: "Atalanta Border",
    description: "La Dea blue and black. Bergamo's fearless goddess.",
    price: 10000,
    color: "#1E5AA8",
    borderPalette: ["#1E5AA8", "#000000"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-lazio",
    name: "Lazio Border",
    description: "Biancocelesti. Sky and white Roman eagles.",
    price: 10000,
    color: "#87D1F9",
    borderPalette: ["#87D1F9", "#FFFFFF"],
    borderStyle: "split-vertical",
  }),

  // === FRANCE ===
  footballBorder({
    id: "profile-border-rotating-psg",
    name: "Paris Saint-Germain Border",
    description: "Navy, red and gold. Parisian luxury and power.",
    price: 10000,
    color: "#004170",
    borderPalette: ["#004170", "#DA291C", "#C6A962"],
    borderStyle: "conic-slice",
  }),

  // === SPAIN CLUBS ===
  footballBorder({
    id: "profile-border-rotating-real-madrid",
    name: "Real Madrid Border",
    description: "All white with royal gold. The kings of Europe.",
    price: 10000,
    color: "#FFFFFF",
    borderPalette: ["#FFFFFF", "#C6A962", "#6B2D7B"],
    borderStyle: "conic-slice",
  }),
  footballBorder({
    id: "profile-border-rotating-barcelona",
    name: "FC Barcelona Border",
    description: "Blaugrana stripes. More than a club.",
    price: 10000,
    color: "#004D98",
    borderPalette: ["#004D98", "#A50044"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-atletico-madrid",
    name: "Atlético Madrid Border",
    description: "Red and white war stripes. Cholo intensity.",
    price: 10000,
    color: "#CB3524",
    borderPalette: ["#CB3524", "#FFFFFF"],
    borderStyle: "split-vertical",
  }),

  // === TURKEY CLUBS ===
  footballBorder({
    id: "profile-border-rotating-galatasaray",
    name: "Galatasaray Border",
    description: "Cimbom red and yellow. The lions of Istanbul.",
    price: 10000,
    color: "#E31837",
    borderPalette: ["#E31837", "#FBBF16"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-fenerbahce",
    name: "Fenerbahçe Border",
    description: "Sarı-lacivert. Yellow and deep navy from Kadıköy.",
    price: 10000,
    color: "#FFCC00",
    borderPalette: ["#FFCC00", "#002D62"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-besiktas",
    name: "Beşiktaş Border",
    description: "Black and white eagles. Çarşı spirit.",
    price: 10000,
    color: "#000000",
    borderPalette: ["#000000", "#FFFFFF"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-trabzonspor",
    name: "Trabzonspor Border",
    description: "Bordo-mavi. Black Sea passion in claret and blue.",
    price: 10000,
    color: "#5C0A1E",
    borderPalette: ["#5C0A1E", "#1E3A8A", "#FCD116"],
    borderStyle: "tricolor-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-goztepe",
    name: "Göztepe Border",
    description: "İzmir red and yellow. The goats from the Aegean.",
    price: 10000,
    color: "#B71C1C",
    borderPalette: ["#B71C1C", "#FFC107"],
    borderStyle: "split-vertical",
  }),

  // === NATIONAL TEAMS ===
  footballBorder({
    id: "profile-border-rotating-england-nt",
    name: "England National Border",
    description: "Three Lions white and red. St George's cross pride.",
    price: 10000,
    color: "#FFFFFF",
    borderPalette: ["#FFFFFF", "#C8102E"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-germany-nt",
    name: "Germany National Border",
    description: "Weiß, Schwarz, Rot. Machine-like efficiency in tricolor.",
    price: 10000,
    color: "#FFFFFF",
    borderPalette: ["#FFFFFF", "#000000", "#DD0000"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-italy-nt",
    name: "Italy National Border",
    description: "Azzurri. Timeless Italian blue.",
    price: 10000,
    color: "#003399",
    borderPalette: ["#003399", "#FFFFFF"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-france-nt",
    name: "France National Border",
    description: "Bleu, Blanc, Rouge. World champions in tricolor glory.",
    price: 10000,
    color: "#002395",
    borderPalette: ["#002395", "#FFFFFF", "#ED2939"],
    borderStyle: "tricolor-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-belgium-nt",
    name: "Belgium National Border",
    description: "Red Devils. Gold and black Belgian fire.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#FCD116", "#000000"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-netherlands-nt",
    name: "Netherlands National Border",
    description: "Oranje. Electric Dutch orange.",
    price: 10000,
    color: "#FF6600",
    borderPalette: ["#FF6600", "#FFFFFF"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-spain-nt",
    name: "Spain National Border",
    description: "La Roja. Red and gold Spanish dominance.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#F1BF00"],
    borderStyle: "edge-stripe",
  }),
  footballBorder({
    id: "profile-border-rotating-turkey-nt",
    name: "Türkiye National Border",
    description: "Ay-Yıldız. Red and white Turkish passion.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#FFFFFF"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-austria-nt",
    name: "Austria National Border",
    description: "Red and white. Alpine elegance.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#FFFFFF"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-denmark-nt",
    name: "Denmark National Border",
    description: "Danish Dynamite. Classic red and white.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#FFFFFF"],
    borderStyle: "stadium-glow",
  }),
  footballBorder({
    id: "profile-border-rotating-sweden-nt",
    name: "Sweden National Border",
    description: "Blågult. Yellow and blue Nordic steel.",
    price: 10000,
    color: "#FFCC00",
    borderPalette: ["#FFCC00", "#004B87"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-switzerland-nt",
    name: "Switzerland National Border",
    description: "Red with white cross. Precise and clean.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#FFFFFF"],
    borderStyle: "conic-slice",
  }),
  footballBorder({
    id: "profile-border-rotating-poland-nt",
    name: "Poland National Border",
    description: "Biało-Czerwoni. White and red.",
    price: 10000,
    color: "#FFFFFF",
    borderPalette: ["#FFFFFF", "#C8102E"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-norway-nt",
    name: "Norway National Border",
    description: "Red, white and deep blue. Viking spirit.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#00205B", "#FFFFFF"],
    borderStyle: "tricolor-band",
  }),
  footballBorder({
    id: "profile-border-rotating-finland-nt",
    name: "Finland National Border",
    description: "White and blue. Nordic ice and fire.",
    price: 10000,
    color: "#003087",
    borderPalette: ["#003087", "#FFFFFF"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-usa-nt",
    name: "United States National Border",
    description: "Stars and stripes. Red, white and blue.",
    price: 10000,
    color: "#B22234",
    borderPalette: ["#B22234", "#FFFFFF", "#3C3B6E"],
    borderStyle: "conic-slice",
  }),
  footballBorder({
    id: "profile-border-rotating-canada-nt",
    name: "Canada National Border",
    description: "Maple leaf red and white.",
    price: 10000,
    color: "#C8102E",
    borderPalette: ["#C8102E", "#FFFFFF"],
    borderStyle: "split-diagonal",
  }),
  footballBorder({
    id: "profile-border-rotating-argentina-nt",
    name: "Argentina National Border",
    description: "Celeste y blanco. Albiceleste magic.",
    price: 10000,
    color: "#74ACDF",
    borderPalette: ["#74ACDF", "#FFFFFF"],
    borderStyle: "pinstripe",
  }),
  footballBorder({
    id: "profile-border-rotating-brazil-nt",
    name: "Brazil National Border",
    description: "Verde e amarelo. The beautiful game in green and gold.",
    price: 10000,
    color: "#009739",
    borderPalette: ["#009739", "#FEDD00"],
    borderStyle: "split-vertical",
  }),
  footballBorder({
    id: "profile-border-rotating-japan-nt",
    name: "Japan National Border",
    description: "Samurai Blue and white. Rising sun discipline.",
    price: 10000,
    color: "#FFFFFF",
    borderPalette: ["#FFFFFF", "#BC002D"],
    borderStyle: "edge-stripe",
  }),
];
